### ISSUE TITLE
IOS运行报RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by Panmax** [attentiveness/reading#1]
```
/Users/pan/GitHub/reading/node_modules/react-native-wechat/ios/RCTWeChat.h:10:9: 'RCTBridgeModule.h' file not found
```

**Comment by Richard-Cao** [comment]
目前reading我在版本更新的时候没做ios的兼容，版本稳定后我会做ios兼容的

**Comment by Richard-Cao** [comment]
这个bug是更新了react-native-wechat到1.3.0出现的，我会修复这个问题

**Comment by Richard-Cao** [comment]
change `RCTWebChat.xcodeproj` → `Build Settings` → `Search Paths` → `Header Search Paths` to
`$(SRCROOT)/../../react-native/React` and
`$(SRCROOT)/../../react-native/Libraries`
