### ISSUE TITLE
分享到微信的功能在真机上调试的时候也提示没有安装微信啊。。

### ISSUE THREAD

**Issue by ElvisVern** [attentiveness/reading#10]
= =  求解

**Comment by Richard-Cao** [comment]
https://github.com/attentiveness/reading/blob/master/ios/reading/Info.plist

**Comment by panxinyang2014** [comment]
Info.plist有错别字，应该把LSApplicationQueriesSchemas 改成 LSApplicationQueriesSchemes

**Comment by Richard-Cao** [comment]
…… @panxinyang2014 感谢提醒，我一直都没注意到……已改
