### ISSUE TITLE
为什么我运行出来的 app是红色错误页面?

### ISSUE THREAD

**Issue by lenkamao** [attentiveness/reading#101]

**Comment by Richard-Cao** [comment]
报错信息是什么，能贴张图吗？

**Comment by candledragle** [comment]
![wechatimg152](https://user-images.githubusercontent.com/8554586/31857229-824a9844-b70b-11e7-97fb-7f659ea0b071.jpeg)
@Richard-Cao

**Comment by Richard-Cao** [comment]
你这个是没启动本地的node server.
用`react-native start`就可以启动了。
