### ISSUE TITLE
你好新手上路，这个项目怎么跑起来，如果 md 文件稍微详细一点就不会问了，盼复

### ISSUE THREAD

**Issue by shiliangL** [attentiveness/reading#103]
你好新手上路，这个项目怎么跑起来，如果 md 文件稍微详细一点就不会问了，盼复

eact-native start 之后出现  ERROR  spawn watchman EAGAIN

**Comment by Richard-Cao** [comment]
`brew uninstall watchman`

`brew install watchman`

重装watchman就行了
