### ISSUE TITLE
进入首页图片没反应

### ISSUE THREAD

**Issue by eggerle** [attentiveness/reading#104]
运行后进入首页，显示图片，为什么摇晃手机或者触摸菜单键都不能触发经典的弹出框进行ip设置？新手求解

**Comment by Richard-Cao** [comment]
我没遇到你这个情况……我一切正常啊……

**Comment by eggerle** [comment]
设置应用权限，允许显示悬浮窗后可以进行ip设置，不过还是在首页图片，进入不了应用。是不是还有什么地方要配置？

**Comment by Richard-Cao** [comment]
进步了应用是什么情况……我也没遇到过……

**Comment by eggerle** [comment]
就是一直停在那张图的界面，reload都不行。server是启动了的，纠结

**Comment by Richard-Cao** [comment]
有什么报错信息吗
