### ISSUE TITLE
clone的代码npm install出错

### ISSUE THREAD

**Issue by miaovictor** [attentiveness/reading#106]
npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated
npm ERR! **Unexpected end of JSON input while parsing near '...obufjs","version":"6.'**

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HYHC\AppData\Roaming\npm-cache\_logs\2017-11-24T04_40_46_720Z-debug.log

**Comment by Richard-Cao** [comment]
你的npm版本多少

**Comment by miaovictor** [comment]
5.4.2

**Comment by miaovictor** [comment]
我之前下载过2.1.0的release源码包，没有问题

**Comment by Richard-Cao** [comment]
那你清下缓存重新install吧，看你这个报错信息没看出什么问题，大概率是下载的时候网络出问题了。建议用yarn

**Comment by miaovictor** [comment]
清缓存没用，不过yarn可以，谢谢

**Comment by Richard-Cao** [comment]
yarn版本是lock的，所以只要我本地没问题，yarn一定没问题。
