### ISSUE TITLE
关于在18:9屏幕上的适配

### ISSUE THREAD

**Issue by HuangQiii** [attentiveness/reading#107]
发现app在18:9的屏幕上可以适配，就是上面贴紧，但是自己写的始终有一条黑色的条，还是16:9的那种显示，看代码也没有发现哪里是关于这个的，麻烦告知

**Comment by Richard-Cao** [comment]
18:9是什么手机？

**Comment by HuangQiii** [comment]
小米mix2
截了作者的APP图和自己的如下，
![_20171127105025](https://user-images.githubusercontent.com/11797760/33248608-d8ab507c-d360-11e7-902b-124295844e8a.jpg)
![_20171127105029](https://user-images.githubusercontent.com/11797760/33248616-da75b514-d360-11e7-8d53-17bdac6ba982.jpg)
您的App可以在18：9上很好的顶到上面（最上面的状态栏颜色设置不考虑，你的还是比我的高），看了代码不知道是怎么设置上去的
thx
还有个小问题，为啥你的最下面的手势栏是白的我是黑的（=。=不过这个并不重要

**Comment by Richard-Cao** [comment]
你说的这个是状态栏颜色，代码里有

**Comment by HuangQiii** [comment]
![tim 20171127112637](https://user-images.githubusercontent.com/11797760/33249512-fc4a8836-d365-11e7-8c33-f946e1df2298.png)
主要是这个，可能我没表达清楚，就是图里的两条红线，你的app可以顶上去

**Comment by Richard-Cao** [comment]
这个你看下https://github.com/attentiveness/reading/blob/master/app/containers/app.js

**Comment by HuangQiii** [comment]
https://github.com/HuangQiii/Qyellow/blob/master/app/containers/app.js
这个是我的react-navigation配置文件，我对比过这里好像没有什么不同

**Comment by Richard-Cao** [comment]
还有Android的style配置。

**Comment by HuangQiii** [comment]
用一种其他方法解决了

声明了最大屏幕高宽比：
在AndroidMainfest.xml里显示声明最大屏幕高宽比（maxinum aspect ratio）
由于传统屏幕为ratio_float=16/9=1.778
普通全免屏ratio_float=18/9=2
三星S8ratio_float=18.5/9=2.056
所以声明个2.1保证可以全部适配
代码如下，
```
<application
      android:name=".MainApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">

      <meta-data
            android:name="android.max_aspect"
            android:value="2.1"/>
            ...
```
感谢作者的解答和给其他小伙伴留个记录

**Comment by Richard-Cao** [comment]
👍

**Comment by shopshow** [comment]
@HuangQiii 非常棒，同用mix2调试
