### ISSUE TITLE
活动标签超过5个的时候一直在闪动

### ISSUE THREAD

**Issue by wtsoftware** [attentiveness/reading#109]
当活动标签超过5个的时候，屏幕会一直闪动。是什么情况!

**Comment by Richard-Cao** [comment]
怎么个闪动法，能给个GIF看看么？

**Comment by yxwandroid** [comment]
我也遇到这个问题了
![2](https://user-images.githubusercontent.com/9635493/33591683-cfca2386-d9c1-11e7-8fc2-db8b40f57fcc.gif)

**Comment by Richard-Cao** [comment]
哇，我感觉出bug了！待我这两天更新一下代码。

**Comment by wtsoftware** [comment]
厉害，已经好了！

**Comment by kingctan** [comment]
没好。还是一直跳。3个都在跳。

**Comment by Richard-Cao** [comment]
@kingctan 代码更新到最新，yarn install之后再看看呢

**Comment by Richard-Cao** [comment]
pull最新的master再跑跑看呢，我本地跑没这个问题了
