### ISSUE TITLE
codepush.getReactPackage is not correct

### ISSUE THREAD

**Issue by johnwonder** [attentiveness/reading#11]
because codepush has update to 1.12.2-beta and codepush  implements reactPackage

so  in mainActivity.java  

this.codePush.getReactPackage() can instead of this.codePush directly

**Comment by Richard-Cao** [comment]
codepush v1.7.0+ support react-native 0.27+，see [reading package.json](https://github.com/attentiveness/reading/blob/master/package.json#L15)

**Comment by Richard-Cao** [comment]
fixed
