### ISSUE TITLE
Execution failed for task ':RCTWeChat:compileReleaseJavaWithJavac'.

### ISSUE THREAD

**Issue by TopGuo** [attentiveness/reading#110]
大佬我运行你项目的时候，出现了一下这个问题，请问如何解决
:RCTWeChat:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':RCTWeChat:compileReleaseJavaWithJavac'.
> Could not find tools.jar. Please check that C:\Program Files\Java\jre1.8.0_151 contains a valid JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.284 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by Richard-Cao** [comment]
你重装一下jdk
