### ISSUE TITLE
请教一个关于安卓的问题，关于虚拟按键抬起遮挡页面的问题

### ISSUE THREAD

**Issue by dreamsk** [attentiveness/reading#111]
华为等手机的虚拟按键抬起遮挡页面的问题，请问下您是怎么解决的？实看你的android端能够根据虚拟按键的起落而更新页面，navigation能够抬起。请问如何解决这个问题呢！

**Comment by Richard-Cao** [comment]
这个我貌似没有做过什么特殊的处理哇……

**Comment by dreamsk** [comment]
嗯，那我看看和你代码的差异了
