### ISSUE TITLE
Error: more than one library with package name 'com.learnium.RNDeviceInfo'

### ISSUE THREAD

**Issue by devzhujiang** [attentiveness/reading#113]
react-native run-android
请问项目启动时报这个错，怎么解决？谢谢了！
Error: more than one library with package name 'com.learnium.RNDeviceInfo'

**Comment by Richard-Cao** [comment]
删掉node_modules，然后用yarn install可以保证没问题。

**Comment by devzhujiang** [comment]
你好，用yarn安装完还是报同样的错误
Error: more than one library with package name 'com.learnium.RNDeviceInfo'
