### ISSUE TITLE
Error:Execution failed for task ':RNDeviceInfo:processDebugResources'. > Error: more than one library with package name 'com.google.android.gms.license'

### ISSUE THREAD

**Issue by yangcf** [attentiveness/reading#116]
你好，我已经尝试了删除node_modul文件夹重新yarn install，但是不能解决问题。
![image](https://user-images.githubusercontent.com/30437860/37818822-7436ef5a-2eb6-11e8-95a5-f367b07cc3e4.png)

**Comment by yangcf** [comment]
@Richard-Cao

**Comment by Richard-Cao** [comment]
我今晚看一下这个问题

**Comment by Richard-Cao** [comment]
昨晚有点忙没顾上看，我今晚看一下哈

**Comment by ppobear** [comment]
把android\build.gradle classpath 'com.android.tools.build:gradle:3.0.0' gradle插件升级到3.0
android\gradle\wrapper\gradle-wrapper.properties distributionUrl=https://services.gradle.org/distributions/gradle-4.1-all.zip
这样修改后就可以编译成功了

**Comment by Richard-Cao** [comment]
问题已经修复。请pull最新的master分支即可。感谢反馈！
