### ISSUE TITLE
react-native start执行时出现以下报错

### ISSUE THREAD

**Issue by LoliTio** [attentiveness/reading#117]
Error: Cannot find module 'babel-plugin-transform-flow-strip-types'

**Comment by LoliTio** [comment]
npm 更新到最新重新安装node_modules还是出现以上问题。babel-plugin-transform-flow-strip-types模块找不到，但是我在node_nodules文件夹中发现有这么一个模块

**Comment by Richard-Cao** [comment]
有试过用yarn install吗

**Comment by Richard-Cao** [comment]
pull最新的master再试试，我这边已经没问题了。

**Comment by LoliTio** [comment]
win10，用yarn没问题了，还用到了这个方法，解决问题了。真机运行OK。https://blog.csdn.net/damoge/article/details/78911145

**Comment by Richard-Cao** [comment]
其实用不上这个我觉得，你正常直接调react-native run-android或者run-ios就可以了，react-native的debug server会自动启动，都不需要主动使用react-native start了。

**Comment by Richard-Cao** [comment]
建议用yarn，因为我上传了yarn的lock，我本地没问题的话，可以保证用yarn别人也没问题。
