### ISSUE TITLE
iOS平台上运行不起来

### ISSUE THREAD

**Issue by dfqin** [attentiveness/reading#118]
刚下载了代码
react-native run-android能正常运行，
react-native run-ios编译报错，报错如下：

ld: warning: directory not found for option '-L/Users/xxx/Desktop/RN/reading-master/ios/iReading'
ld: library not found for -lRNDeviceInfo
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:

	Ld build/Build/Products/Debug-iphonesimulator/iReading.app/iReading normal x86_64
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/reading.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/reading.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by Richard-Cao** [comment]
我今晚看一下这个问题

**Comment by Richard-Cao** [comment]
昨晚没来得及……我今晚看一下

**Comment by Richard-Cao** [comment]
pull最新的master分支，已经解决问题，感谢反馈。
