### ISSUE TITLE
报警高isMountde(...)

### ISSUE THREAD

**Issue by do0ob** [attentiveness/reading#119]
大佬，我运行项目 报一个警告   信息如下 
Warning: isMounted(...) is deprecated in plain JavaScript React classes,instead,make sure to clean up subscriptions and pending requests in componentWillUnmount to pre memory leaks.

改如何处理啊

**Comment by Richard-Cao** [comment]
这个是一个系统warning，暂时我也不知道如何处理，应该是某个库调用到了这个API，个人感觉及时更新各种库就可以，reading的代码里没有主动调用这个API。
