### ISSUE TITLE
网络错误时，弹窗弹出多次

### ISSUE THREAD

**Issue by jqjiang** [attentiveness/reading#12]
有4个分类，就会弹出4次

**Comment by Richard-Cao** [comment]
好的，感谢反馈，这个问题我去fix一下，修复了我会close掉这个issue。

**Comment by Richard-Cao** [comment]
fixed

**Comment by jqjiang** [comment]
建议页只能输入英文，是这样吗




Sent with Unibox

**Comment by Richard-Cao** [comment]
可以输入中文啊 @jqjiang

**Comment by jqjiang** [comment]
可能是因为我在xcode模拟器打开的，不是代码问题




Sent with Unibox
