### ISSUE TITLE
反应问题

### ISSUE THREAD

**Issue by ZhangWei2008** [attentiveness/reading#120]
1有两个tabbar时候，下面的横线分布不均匀 
![qq 20180605104720](https://user-images.githubusercontent.com/19800003/40952519-2493daf8-68ae-11e8-819d-7ccbec3d5f7a.jpg)

**Comment by Richard-Cao** [comment]
我这两天有空了看下这个问题

**Comment by Richard-Cao** [comment]
这个应该已经没问题了
