### ISSUE TITLE
重新选择分类时，首页不能刷新

### ISSUE THREAD

**Issue by ngu2008** [attentiveness/reading#121]
重新选择分类时，首页不能刷新
![qq 20180605105030](https://user-images.githubusercontent.com/19800003/40952578-5ee81b60-68ae-11e8-9f1f-e5072239c655.jpg)

**Comment by Richard-Cao** [comment]
我这两天有空了看下这个问题

**Comment by Richard-Cao** [comment]
我更新了master，你再试试看
