### ISSUE TITLE
启动之后一直停留在首页

### ISSUE THREAD

**Issue by caiya** [attentiveness/reading#122]
早上刚拉取的代码本地跑了一下，结果启动后一直停留在首页不动

![image](https://user-images.githubusercontent.com/12036572/41016251-b552ecd2-6980-11e8-9114-b023d6196f49.png)
![image](https://user-images.githubusercontent.com/12036572/41016257-c32aa142-6980-11e8-8dae-51b8e94640a1.png)

**Comment by Richard-Cao** [comment]
重新yarn install了吗？

**Comment by caiya** [comment]
@Richard-Cao 好了，重装依赖就好了
