### ISSUE TITLE
软键盘顶起底部toolbar布局

### ISSUE THREAD

**Issue by dongdongge** [attentiveness/reading#123]
![3ayq xo k gmc16hqu1 x1](https://user-images.githubusercontent.com/17643741/42070702-4c7d09c4-7b8a-11e8-9dad-a3a723153f59.png)

**Comment by dongdongge** [comment]
软键盘顶起底部toolbar布局

**Comment by Richard-Cao** [comment]
很神奇，我都不知道这个算不算bug……
