### ISSUE TITLE
unable to load script from assets 'index.android bundle'

### ISSUE THREAD

**Issue by Mscynol** [attentiveness/reading#125]
在真机上运行总报这个错误，是什么情况，unable to load script from assets 'index.android bundle'  ,make sure your bundle is packaged correctly or youu're runing a packager server

**Comment by Richard-Cao** [comment]
你用react-native start起本地server了吗？

**Comment by Mscynol** [comment]
全部都起来了，可是依然没解决，后来我把手机切换了一个WIFI就好了，感觉还是不知道问题出在哪，电脑跟手机是在同一个网络上的，真机是小米5
