### ISSUE TITLE
 Could not find common.jar (android.arch.core:common:1.0.0).

### ISSUE THREAD

**Issue by yangqx** [attentiveness/reading#126]
我安装运行项目后出现如下问题  有遇到的吗，怎么解决的？
* What went wrong:
A problem occurred configuring project ':app'.
> Could not find common.jar (android.arch.core:common:1.0.0).
  Searched in the following locations:
      https://jcenter.bintray.com/android/arch/core/common/1.0.0/common-1.0.0.jar

**Comment by yangqx** [comment]
allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        //解决问题：Error:Failed to resolve: android.arch.core:common:1.1.0
        maven { url "https://maven.google.com" }
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

**Comment by Richard-Cao** [comment]
这个问题没遇到过……你现在解决了吗？

**Comment by yangqx** [comment]
是由于“https://jcenter.bintray.com/android/arch/core/common/1.0.0/common-1.0.0.jar”下载失效导致的，修改maven 的配置就可以了
maven { url "https://maven.google.com" }
jcenter()
maven { url 'https://jitpack.io' }
}
