### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by chenai1512** [attentiveness/reading#127]
项目运行是报错，报错信息
TypeError: Cannot convert undefined or null to object

This error is located at:
    in Category (at CategoryContainer.js:48)
    in CategoryContainer (created by Connect(CategoryContainer))
    in Connect(CategoryContainer) (at SceneView.js:17)
    in SceneView (at CardStack.js:455)
    in RCTView (at View.js:60)
    in View (at CardStack.js:454)
    in RCTView (at View.js:60)
    in View (at CardStack.js:453)
    in RCTView (at View.js:60)
    in View (at createAnimatedComponent.js:154)
    in AnimatedComponent (at Card.js:12)
    in Card (at PointerEventsContainer.js:39)
    in Container (at CardStack.js:498)
    in RCTView (at View.js:60)
    in View (at CardStack.js:414)
    in RCTView (at View.js:60)
    in View (at CardStack.js:413)
    in CardStack (at CardStackTransitioner.js:67)
    in RCTView (at View.js:60)
    in View (at Transitioner.js:142)
    in Transitioner (at CardStackTransitioner.js:19)
    in CardStackTransitioner (at StackNavigator.js:41)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:226)
    in NavigationContainer (at root.js:31)
    in Provider (at root.js:30)
    in Root (at renderApplication.js:33)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:60)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:32)
另外从应用商店下载的应用ios端闪退android端首页白屏

**Comment by Richard-Cao** [comment]
删了node_modules重新yarn install应该就好了。
应用商店的APP已经没维护了，现在只维护代码。

**Comment by xiaosenlin** [comment]
我也遇到这个问题了，重新安装了也不行，好像两周前运行还是好的，
是不是leancloud出现问题了？
谢谢~

**Comment by Richard-Cao** [comment]
今晚我看一下这个问题

**Comment by chenai1512** [comment]
我自己已经解决了，这个代码报错是在Category,js这个文件里面的91行，获取不到标签分类，根本原因是源代码里面的showapi过期了无法使用，自己showapi管网申请一个买一下把UrlUtils里面的密钥替换掉就好了。

**Comment by Richard-Cao** [comment]
居然已经过期了，看来我晚上要重新申请一下了……非常感谢 @chenai1512

**Comment by ZhaoJiYue** [comment]
接口怎么弄呢？一直不通

**Comment by Richard-Cao** [comment]
[ShowAPI](https://www.showapi.com/api/lookPoint/582/2) was used by iReading from free to charge, so my key doesn't work. You could apply for a new key and replace in [UrlUtil.js](https://github.com/attentiveness/reading/blob/master/app/utils/UrlUtil.js), it will work properly.

I apologize to inconvenience you.

**Comment by xiangangYu** [comment]
我也遇到同样的问题

**Comment by Richard-Cao** [comment]
https://github.com/attentiveness/reading#importance   @xiangangYu

**Comment by fengdesola** [comment]
我刚开始接触，请教下怎么定位这种错误，从报错看就知道Category.js有问题@chenai1512 @Richard-Cao

**Comment by Tim1437** [comment]
我注册ShowAP帐号，需要新建API吗。还是我也要付费后才能使用，能否提供一些更改KEY方面的指引，没用过ShowAPI

**Comment by Richard-Cao** [comment]
这个API现在变成了付费才能使用了…… @Tim1437

**Comment by gejiashu** [comment]
showapi_appid:85481
showapi_sign:8c715c0272e241bbbb54280a522334b2
贡献一个刚买的appid,替换掉UrlUtil.js中的就没问题了

**Comment by Richard-Cao** [comment]
@gejiashu 非常感谢！如果可以的话方便提个pr替换吗？

**Comment by Richard-Cao** [comment]
@gejiashu 非常感谢！

**Comment by dengbaoling** [comment]
![image](https://user-images.githubusercontent.com/17171011/62306351-4bc7a980-b4b4-11e9-9bad-fbd0a150ce39.png)
这个是什么错误
![Uploading image.png…]()

**Comment by lqliqiong** [comment]
> @gejiashu 非常感谢！如果可以的话方便提个pr替换吗？

这个账号也不能用了，自己申请账号 里面的接口规范怎么维护了

**Comment by Richard-Cao** [comment]
> > @gejiashu 非常感谢！如果可以的话方便提个pr替换吗？
> 
> 这个账号也不能用了，自己申请账号 里面的接口规范怎么维护了

心塞

**Comment by wanwenyun** [comment]
请问，这个问题现在有好的解决办法了吗？

**Comment by Richard-Cao** [comment]
> 请问，这个问题现在有好的解决办法了吗？

我的账号失效了……

**Comment by zhangxu1123** [comment]
怎么用showapi 呢，我注册账号之后，怎么弄

**Comment by nozbwang** [comment]
> 怎么用showapi 呢，我注册账号之后，怎么弄

直接购买 [https://www.showapi.com/apiGateway/view?apiCode=582这个数据接口，用你自己的showapi_appid](https://www.showapi.com/apiGateway/view?apiCode=582%E8%BF%99%E4%B8%AA%E6%95%B0%E6%8D%AE%E6%8E%A5%E5%8F%A3%EF%BC%8C%E7%94%A8%E4%BD%A0%E8%87%AA%E5%B7%B1%E7%9A%84showapi_appid) 和 showapi_sign 替换下面图片中的文件中对应的showapi_appid 和 showapi_sign 既可以解决：
> ![image](https://user-images.githubusercontent.com/3433318/60341421-027dc900-99e1-11e9-9dcb-f329c1addd91.png)
