### ISSUE TITLE
app打开白屏

### ISSUE THREAD

**Issue by yin-shu** [attentiveness/reading#131]
我新下载的App2.1.0，打开是闪一下就白屏，换了两个手机荣耀和小米的，同样效果

**Comment by yin-shu** [comment]
那这个项目你还维护吗，这个App还更新吗

**Comment by yin-shu** [comment]
@Richard-Cao

**Comment by Richard-Cao** [comment]
我关注关注这个接口，如果一直是不可用状态，就没法继续维护了……

**Comment by yin-shu** [comment]
如果接口不能用了，能不能弄些假数据，以供来学习的同学能打开App，继续学习您的代码

**Comment by Richard-Cao** [comment]
你说的有道理，我考虑下怎么做。

**Comment by yin-shu** [comment]
期待中。。。

**Comment by hotdog45** [comment]
ios 打开一直在启动页,一动不动.需要改哪里?

**Comment by Richard-Cao** [comment]
接口key @hotdog45 readme里写了

**Comment by Richard-Cao** [comment]
#132
