### ISSUE TITLE
网络发生错误，请重试

### ISSUE THREAD

**Issue by wickey-w** [attentiveness/reading#134]
报错如图https://i.niupic.com/images/2019/02/27/5PjV.png

**Comment by Richard-Cao** [comment]
是不是api的原因

**Comment by wickey-w** [comment]
怎么看是不是api的原因？我是个新手

**Comment by Richard-Cao** [comment]
抓个包看看

**Comment by wickey-w** [comment]
https://i.niupic.com/images/2019/02/28/5Ppr.jpg
只有route.showapi.com这个接口有返回值，其他接口都抓不到数据

**Comment by Richard-Cao** [comment]
#133 看下这个
