### ISSUE TITLE
数据接口过期

### ISSUE THREAD

**Issue by ivanyb** [attentiveness/reading#139]
![image](https://user-images.githubusercontent.com/3433318/60340538-766aa200-99de-11e9-87e9-a47564ed58c6.png)

在Android端打开后包如下错误，然后我试了一下，http://route.showapi.com/582-2 这个接口，提示请求数量用完了，我想自己去万维易源https://www.showapi.com注册一个appid，但是不知道http://route.showapi.com/582-2 这些接口作者用的是哪个分类下的数据呢。麻烦告知一下，我去注册该分类的api，谢谢，我的邮箱是：ivanyb@qq.com

**Comment by ivanyb** [comment]
已经找到了连接了
各位如果有问题，直接购买 https://www.showapi.com/apiGateway/view?apiCode=582这个数据接口，用你自己的showapi_appid 和 showapi_sign 替换下面图片中的文件中对应的showapi_appid 和 showapi_sign 既可以解决：
![image](https://user-images.githubusercontent.com/3433318/60341421-027dc900-99e1-11e9-9dcb-f329c1addd91.png)

**Comment by Richard-Cao** [comment]
👍
