### ISSUE TITLE
应该怎么做才能运行起来？

### ISSUE THREAD

**Issue by chongxx** [attentiveness/reading#14]
我直接clone了项目到本地然后
`dashzhao@dashdeMacBook-Pro:~/Learn/reactNative$ git clone https://github.com/attentiveness/reading.git
Cloning into 'reading'...
remote: Counting objects: 1509, done.
remote: Compressing objects: 100% (76/76), done.
remote: Total 1509 (delta 25), reused 0 (delta 0), pack-reused 1429
Receiving objects: 100% (1509/1509), 1.77 MiB | 120.00 KiB/s, done.
Resolving deltas: 100% (822/822), done.
Checking connectivity... done.
dashzhao@dashdeMacBook-Pro:~/Learn/reactNative$ ls
AwesomeProject	Hello		UseView		reading
dashzhao@dashdeMacBook-Pro:~/Learn/reactNative$ cd reading/
dashzhao@dashdeMacBook-Pro:~/Learn/reactNative/reading$ ls
LICENSE				Reading_OnLine_Accident.md	index.android.js		package.json
README.md			android				index.ios.js			screenshot
Reading_Logo.png		app				ios
dashzhao@dashdeMacBook-Pro:~/Learn/reactNative/reading$ react-native run-android
Command `run-android` unrecognized. Did you mean to run this inside a react-native project?`
刚开始学习RN所以不知道怎么做
-------------
好了我知道怎么做了 ， 
需要`npm install` 这样下载package.json 里的依赖

**Comment by Richard-Cao** [comment]
我在readme里说明了呀……按照步骤操作就可以啦
