### ISSUE TITLE
RCTBridgeModule.h

### ISSUE THREAD

**Issue by igo903** [attentiveness/reading#15]

**Comment by ronniegong** [comment]
same problem

**Comment by Richard-Cao** [comment]
what problem?

**Comment by mywentu** [comment]
npm install后，在xcode run  ，报错 “RCTBridgeModule.h not found” @Richard-Cao

**Comment by Richard-Cao** [comment]
`RCTBridgeModule.h`是react-native的iOS原生代码里的，这说明少依赖了，你检查下你的工程。应该和代码没关系，我一直run都是正常的 @mywentu

**Comment by Richard-Cao** [comment]
check this #1
