### ISSUE TITLE
运行报错，TypeError：Object is null or undefined

### ISSUE THREAD

**Issue by wanwenyun** [attentiveness/reading#158]
![image](https://user-images.githubusercontent.com/49218620/68586190-0f4a1780-04bf-11ea-9cba-27d9f26a0419.png)
看到前面也有人有这个问题，想知道现在有解决办法了吗？

**Comment by shuidaan** [comment]
同求这个问题 请问怎么解决的？？？

**Comment by shuidaan** [comment]
![image](https://user-images.githubusercontent.com/24624971/70886224-ee249b80-2015-11ea-9735-0c569985e4e8.png)

**Comment by Richard-Cao** [comment]
#127
