### ISSUE TITLE
react-native start 后 页面只展示 React Native packager is running

### ISSUE THREAD

**Issue by mamababa** [attentiveness/reading#159]
React Native packager is running
请问怎么解决？页面出不来

**Comment by Richard-Cao** [comment]
没明白是什么意思

**Comment by xiaotuoapi** [comment]
> 没明白是什么意思
老哥，他的意思是这样的，我的也出现了，如图：
![image](https://user-images.githubusercontent.com/25766465/69318497-3e5b4880-0c78-11ea-8c41-25973130765a.png)

**Comment by Richard-Cao** [comment]
server没起？

**Comment by xiaotuoapi** [comment]
> server没起？

服务起了

**Comment by Richard-Cao** [comment]
这个看起来是react-native没配置好 报什么错

**Comment by xiaotuoapi** [comment]
> 这个看起来是react-native没配置好 报什么错

老哥，解决了，程序ok了，谢谢老哥，换了一下网络，好了.....尴尬
