### ISSUE TITLE
TypeError:Network request failed

### ISSUE THREAD

**Issue by otawa811** [attentiveness/reading#16]
你好，我想请教下 我仿照案例新建了一个Demo，然后一点一点照搬代码去理解，运行之后，Android可以显示出来 新闻列表数据，但是 Ios显示 TypeError:Network request failed 这个错误。

**Comment by Richard-Cao** [comment]
@otawa811 这说明网络请求没成功。。。有可能是请求没发出去，你看下是不是代码有啥问题

**Comment by otawa811** [comment]
@Richard-Cao 不是代码问题，问题已经解决了，没来的急发。
Xcode工程  Info.plist 里 添加 App Transport Security Settings －》Allow Arbitrary Loads 设置为true就可以了。

**Comment by Richard-Cao** [comment]
good job
