### ISSUE TITLE
老哥，运行完readme.md文件的操作后，运行react-native run-android 报下面问题

### ISSUE THREAD

**Issue by xiaotuoapi** [attentiveness/reading#160]
![image](https://user-images.githubusercontent.com/25766465/69222396-56699400-0bb4-11ea-9737-d9f0ac48b857.png)
$ react-native run-android
Scanning folders for symlinks in D:\jofiy\app_workplaces\reading\node_modules (112ms)
JS server already running.
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'reading'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not download gradle-core.jar (com.android.tools.build:gradle-core:2.3.3)
      > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle-core/2.3.3/gradle-core-2.3.3.jar'.
         > Could not GET 'https://d29vzk4ow07wi7.cloudfront.net/915a87617b5936762ec7ac43cfea1e0a86443c02ecbb5eb5c6a7e596f9866d3c?response-content-disposition=attachment%3Bfilename%3D%22gradle-core-2.3.3.jar%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvOTE1YTg3NjE3YjU5MzY3NjJlYzdhYzQzY2ZlYTFlMGE4NjQ0M2MwMmVjYmI1ZWI1YzZhN2U1OTZmOTg2NmQzYz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmdyYWRsZS1jb3JlLTIuMy4zLmphciUyMiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU3NDIzOTQ0Mn0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=Cj~UIOqchZQTtJyc7Cx1-Cd4g5r0Sf4jnq7xRUWmK0hTUWdAWbcY6uoin6LdjO-Bc9K2bfILfB3QxJiIjc8rSvxA71~yTgYCTMAe1KXFTHUo5JXN2pyikOnA7wcLrj3w2HRS-esbGBezxFIxHC7Zksxr11wqYBzbexP3QlBG7JizUOmWhiLjqdyON6VYQ7un3KequjeJzGsGX8yfvutEQkX86SKikbKdBDQkdIgkUAQS3o8C73VXqefR-HnKDtbefP18vNnbKNySDFINWSZTWk-~8y-Y9UDWzhU-9MVXKaLt0jhsVnrcE9eXvzAGcNb5I7cAx6lh5U28Elq7Ws3GxQ__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA'.

**Comment by xiaotuoapi** [comment]
心塞啊，老哥

**Comment by Richard-Cao** [comment]
这看起来是你网络不通……

**Comment by xiaotuoapi** [comment]
这破网速，哎

**Comment by xiaotuoapi** [comment]
> 这看起来是你网络不通……

这破网，哎

**Comment by Richard-Cao** [comment]
> > 这看起来是你网络不通……
> 
> 这破网，哎

这我就没辙了……
