### ISSUE TITLE
react-native run-ios 报错

### ISSUE THREAD

**Issue by codingEcho** [attentiveness/reading#17]
.../reading/node_modules/promise/lib/done.js:10
      throw err;
      ^

Error: xcodebuild process exited with code 65
    at ChildProcess.<anonymous> (runIOS.js:102:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

**Comment by Richard-Cao** [comment]
log不全啊。看下 #1 能不能解决你的问题

**Comment by codingEcho** [comment]
按照#1的方法试了试，还是找不到RCTBridgeModule.h @Richard-Cao

**Comment by Richard-Cao** [comment]
@codingEcho 是wechat那个库报的问题么

**Comment by codingEcho** [comment]
是的，现在
修改了
$(SRCROOT)/../../react-native/React and
$(SRCROOT)/../../react-native/Libraries
但是又抛另外一个错
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/Developer/Library/Frameworks'
ld: file not found: /Users/mlwills/Library/Developer/Xcode/DerivedData/reading-evusolphipkzgrgghdzjodzlcllk/Build/Products/Debug-iphonesimulator/reading.app/reading
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Richard-Cao** [comment]
这是你xcode里虚拟机的问题了，就不是代码问题啦 @codingEcho

**Comment by codingEcho** [comment]
@Richard-Cao 难道是我的版本太高 不兼容

**Comment by Richard-Cao** [comment]
额，你把编译虚拟机sdk降一点试试，估计是你没有9.3的虚拟机导致的

**Comment by codingEcho** [comment]
@Richard-Cao 把readingTests删除之后问题解决[这里](http://stackoverflow.com/questions/35234373/directory-not-found-for-option-f-applications-xcode-app-developer-library-f)

**Comment by Richard-Cao** [comment]
good

**Comment by HasBeenOnGit** [comment]
@codingEcho 在哪把readingTests删除?

**Comment by Richard-Cao** [comment]
你现在拉最新的代码，readingTests已经删除掉了  @HasBeenOnGit

**Comment by HasBeenOnGit** [comment]
恩,好了.重新弄了最新的代码,一个问题都没有了.
