### ISSUE TITLE
UnKnown module "react-native-root-modal"

### ISSUE THREAD

**Issue by youxikaifa** [attentiveness/reading#2]
npm install 后，在代码中加import Modal from 'react-native-root-modal';
报标题的错误，是没安装上去还是怎么回事？

**Comment by Richard-Cao** [comment]
reading项目中没有使用`react-native-root-modal`依赖，如果自己使用了那么需要npm install安装成功之后就可以使用了

**Comment by youxikaifa** [comment]
已解决，在npm install react-native-root-modal之前，先安装npm install react-native-root-siblings

**Comment by Richard-Cao** [comment]
good
