### ISSUE TITLE
请教,关于store一些问题 

### ISSUE THREAD

**Issue by JasonStu** [attentiveness/reading#23]
你好!我对store 最后configureStore(initialState) 这方法不太懂想请教一下

export default function configureStore(initialState) {
  const store = createStoreWithMiddleware(rootReducer, initialState);

  return store;
}

**Comment by Richard-Cao** [comment]
可以看下这里 [createStoreWithMiddleware](http://cn.redux.js.org/docs/advanced/Middleware.html)
