### ISSUE TITLE
闪屏

### ISSUE THREAD

**Issue by otawa811** [attentiveness/reading#24]
你好，我想请问下，APP在加载完 IOS的 LaunchImage 之后 会闪一下白屏，然后再跳转到 Splash 页面，这个该怎么处理呢？

**Comment by Richard-Cao** [comment]
那个是模拟器上才有的吧，真机应该是没有的，你用真机试试？

**Comment by otawa811** [comment]
我是用的真机调的。

**Comment by otawa811** [comment]
@Richard-Cao 我试了下，跳转到其它页面也一样会先闪一下白屏然后再跳转。

**Comment by Richard-Cao** [comment]
我刚又跑起来看了看，没白屏啊……

**Comment by otawa811** [comment]
@Richard-Cao 定位的问题大概在Xcode的APPDelegate这里，我把 alpha:1 改为 0，闪的白屏就变黑了。
这行注释掉也不行，是不是因为加载 Bundle 比较慢，所以显示的 RootView 背景色。

`  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;`

**Comment by Richard-Cao** [comment]
这个我也不是很清楚，这部分代码就是react-native init出来的，我没改动过，只是加了codepush的bundle

**Comment by otawa811** [comment]
@Richard-Cao 问题已解决，IOS版 起因是刚才发的那个。
解决方法是在 RCTRootView 下有一个 loadingView

```
/**
 * A view to display while the JavaScript is loading, so users aren't presented
 * with a blank screen. By default this is nil, but you can override it with
 * (for example) a UIActivityIndicatorView or a placeholder image.
 */
@property (nonatomic, strong) UIView *loadingView;
```

通过这个loadingView 在APPDelegate加如下代码
```
  UIImageView *loadingView = [[UIImageView alloc] initWithImage:[UIImage imageNamed:@"splash.png"]];
  loadingView.frame = [UIScreen mainScreen].bounds;
  rootView.loadingView = loadingView;
```

**Comment by Richard-Cao** [comment]
相当于在原生代码里加一个loadingview么？ @otawa811

**Comment by otawa811** [comment]
@Richard-Cao 对，通过原生代码覆盖  #import "RCTRootView.h"  里面提供的 loadingview，就可以了。

**Comment by Richard-Cao** [comment]
加上这个loadingview是个什么效果？

**Comment by otawa811** [comment]
@Richard-Cao 启动界面无缝跳转Splash界面，不再是之前的会闪1下。

**Comment by Richard-Cao** [comment]
有没有兴趣提个pr，在comment里加上2个动图，加这个前和加这个后~~

**Comment by otawa811** [comment]
@Richard-Cao 有RN交流的QQ群吗

**Comment by Richard-Cao** [comment]
我加的 @jiangqqlmj 的QQ群

**Comment by Richard-Cao** [comment]
我加的 @jiangqqlmj 的QQ群

**Comment by otawa811** [comment]
@Richard-Cao 你在几群，以后有问题方便沟通交流。

**Comment by Richard-Cao** [comment]
1群

**Comment by Richard-Cao** [comment]
欢迎PR
