### ISSUE TITLE
run-ios

### ISSUE THREAD

**Issue by vistier** [attentiveness/reading#25]
Installing build/Build/Products/Debug-iphonesimulator/reading.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
Failed to install the requested application
An application bundle was not found at the provided path.
Provide a valid path to the desired application bundle.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/reading.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

**Comment by Richard-Cao** [comment]
Use `Xcode` to run and try again.
