### ISSUE TITLE
打包时插件有问题

### ISSUE THREAD

**Issue by codeHui** [attentiveness/reading#26]
A problem occurred configuring project ':RNDeviceInfo'.
> Could not resolve all dependencies for configuration ':RNDeviceInfo:_debugCompile'.
   > Could not find com.google.android.gms:play-services-gcm:8.3.0.
     Searched in the following locations:
         file:/C:/Users/Administrator/.m2/repository/com/google/android/gms/play-services-gcm/8.3.0/play-services-gcm-8.3.0.pom
         file:/C:/Users/Administrator/.m2/repository/com/google/android/gms/play-services-gcm/8.3.0/play-services-gcm-8.3.0.jar
         https://jcenter.bintray.com/com/google/android/gms/play-services-gcm/8.3.0/play-services-gcm-8.3.0.pom
         https://jcenter.bintray.com/com/google/android/gms/play-services-gcm/8.3.0/play-services-gcm-8.3.0.jar
         file:/E:/works/rn/gitphoto/reading/node_modules/node_modules/react-native/android/com/google/android/gms/play-services-gcm/8.3.0/play-services-gcm-8.3.0.pom
         file:/E:/works/rn/gitphoto/reading/node_modules/node_modules/react-native/android/com/google/android/gms/play-services-gcm/8.3.0/play-services-gcm-8.3.0.jar
         file:/D:/codes/android-sdk-windows/extras/android/m2repository/com/google/android/gms/play-services-gcm/8.3.0/play-services-gcm-8.3.0.pom
         file:/D:/codes/android-sdk-windows/extras/android/m2repository/com/google/android/gms/play-services-gcm/8.3.0/play-services-gcm-8.3.0.jar
     Required by:           
         reading:RNDeviceInfo:unspecified
原因在此
https://github.com/rebeccahughes/react-native-device-info/issues/78

**Comment by Richard-Cao** [comment]
额，我并没有用gms……我打包都是正常的，没遇到过这个错误

**Comment by codeHui** [comment]
@Richard-Cao 你是用苹果打包吗？

**Comment by Richard-Cao** [comment]
是的，mac
