### ISSUE TITLE
Build failure with an exception

### ISSUE THREAD

**Issue by LeonJavaAndroid** [attentiveness/reading#3]
* What went wrong:
Execution failed for task ':RNDeviceInfo:prepareComAndroidSupportAppcompatV72220Library'.
> Could not expand ZIP 'D:\ProgramFiles\android_sdk\extras\android\m2repository\com\android\support\appcompat-v7\22.2.0\appcompat-v7-22.2.0.aar'.

我的sdk目录下是存在这个aar的

**Comment by Richard-Cao** [comment]
sdk里的support升级到最新了吗
