### ISSUE TITLE
一些反馈

### ISSUE THREAD

**Issue by kinkk** [attentiveness/reading#30]
- BUG
  多列表共享store相同数据（reducer - read）

```
  isRefreshing: false,
  loading: false,
  isLoadMore: false,
  noMore: false,
```

造成展示状态混乱，不同列表应对应不同状态

多列表共享page 数据展示错误
比如列表1到了第10页，列表二才刚展示，但是加载更多的时候就是从第11页开始的
- 结构建议
  应继续分层
  列表应单独出来 （page/Feeds）结构和代码会清晰很多

**Comment by Richard-Cao** [comment]
good，这部分是我欠考虑了，但是不同列表对应不同状态又会过于复杂，我感觉其实是可以统一管理的，如果你有想法的话，提个PR如何？我也想想应该怎么改这个问题

**Comment by Richard-Cao** [comment]
结构建议很好，Main.js确实有些复杂了，这部分我考虑下怎么拆

**Comment by kinkk** [comment]
结构分拆可以解决问题，列表拆成feedsView，对应着下面的状态

>   isRefreshing: false,
>   loading: false,
>   isLoadMore: false,
>   noMore: false,
>   page

只不过需要修改store结构 如read - reducer
```
case types.RECEIVE_ARTICLE_LIST:
      let alias = action.alias;
      return _.merge({}, state, {[categoryId]: {
        isRefreshing: false,
        isLoadMore: false,
        noMore: action.list.length != 20,
        list: state[alias] && state[alias].isLoadMore ? loadMore(state, action) : combine(state, action),
        loading: false//state[alias].list === undefined
      }});
```
相当于read（store）里面每个列表结构如下
```
categoryId ->
    isRefreshing
    isLoadMore
    noMore
    list
    loading
```

feedsView 连接 read reducer，传入pros （category id）
```
function select(store, props) {
  let initialSate = {
    isRefreshing: false,
    loading: false,
    isLoadMore: false,
    noMore: false,
    list: []
  };

  return {
    feeds: store.read[props.categoryId] || initialSate
  };
}
```

目前东西基于reading做了不少改动，稍后有时间我整下下，提交个PR

**Comment by Richard-Cao** [comment]
@kinkk good!期待PR

**Comment by xks19943** [comment]
你好，我下载安装了apk出现问题，我觉得可能是我4.4系统的原因，下载源码安装的时候也不能安装成功，提示是不能发现leandcolud-storage 下面的 ./qinniu/io.js .

**Comment by Richard-Cao** [comment]
@xks19943 你看一下 #8 啊。。。。

**Comment by xks19943** [comment]
好的 明白了 感谢大大

**Comment by yanbober** [comment]
@kinkk 能稍微详细的说说具体方案吗？谢谢，QQ：373131686

**Comment by Gantios** [comment]
iphone 6 卡顿非常明显，特别是进去文章点返回时，还有点击底部标签了切换，不知道是不是我操作姿势不对~！

**Comment by Richard-Cao** [comment]
@Gantios 你用的什么包，debug包真机调试的么

**Comment by hello3ds** [comment]
你好，我想问下 那些React 的库怎么导入啊，为什么我打开ios的 看到下面的 Libraries  中的都是置灰的。刚入ReactNative坑，请问该怎么导入啊。谢谢qq：961726183

**Comment by Richard-Cao** [comment]
@hello3ds run `npm install`

**Comment by lakeoffaith** [comment]
@hello3ds   `npm install`

**Comment by Richard-Cao** [comment]
Simple fix this bug.
