### ISSUE TITLE
About minSDK version

### ISSUE THREAD

**Issue by keanuyaoo** [attentiveness/reading#31]
Yoy said that  it support Android 4.1 (API 16)+
But it throw a exception  on API19;
with:
      Caused by: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Attribute     selectableItemBackgroundBorderless couldn't be found in the resource list;

had depend on: com.android.support:appcompat-v7:23.3.0

May I have done something wrong?

**Comment by Richard-Cao** [comment]
I haven't met this error.
Please check npm>=3.x node>=4.x,
then remove node_modules file and run `npm install`,
try again.

**Comment by keanuyaoo** [comment]
env:
      node:v6.4.0
      npm:3.10.3
      react-native-cli:1.0.0
      react-native:0.31.0
It seems that something wrong with android package;
I will check my android env / build tools (windows)
and try  run-android on macos ;
Thanks!

**Comment by keanuyaoo** [comment]
It's plugin: react-native-scrollable-tab-view 's Bug
https://github.com/skv-headless/react-native-scrollable-tab-view/issues/397

**Comment by Richard-Cao** [comment]
@keanuyaoo Thanks! I will stay focused on it.
