### ISSUE TITLE
find a native module error when writing tests

### ISSUE THREAD

**Issue by vmlinz** [attentiveness/reading#36]
@Richard-Cao 

cause: `react-native-root-toasts` does not compile es6 code to es5 when uploading to npm.

when: mocha test with babel-register, it will by default ignore any file that is located in node_modules, so the es6 files in `react-native-root-toasts` will cause test fail.

solution: configure babel to include `react-native-root-toasts` if you used it in your tests or ask the user to compile it to es5 as other npm modules.

I've opened an issue in the original repo: https://github.com/magicismight/react-native-root-toast/issues/16

**Comment by vmlinz** [comment]
/reading/node_modules/react-native-root-toast/index.js:1
(function (exports, require, module, __filename, __dirname) { import Toast from './lib/Toast';
                                                              ^^^^^^
SyntaxError: Unexpected token import

**Comment by vmlinz** [comment]
@Richard-Cao currently fixed by https://github.com/attentiveness/reading/commit/da1902da82165448bc5ef73a8f56a09dcc738856

Now I set ignore to false, so that babel require hook will not ignore node_modules by default.

But anyway, it's the responsibility of the module author to add es5 support in modules.

Br,

**Comment by Richard-Cao** [comment]
Thx！！
