### ISSUE TITLE
[Error] undefined WeChat.registerApp

### ISSUE THREAD

**Issue by lilonghe** [attentiveness/reading#37]
undefined is not an object (evaluating 'WeChat.registerApp')

index.js -> line 183

**Comment by Richard-Cao** [comment]
Delete `node_modules` and `npm install` again.

**Comment by lilonghe** [comment]
and it's also not work. -_-

**Comment by Richard-Cao** [comment]
iOS？or Android？or both？

**Comment by lilonghe** [comment]
ios 10 and mac os 10.12, xcode 8 ...

**Comment by Richard-Cao** [comment]
Only iOS 10?

**Comment by lilonghe** [comment]
9.3 也不行哎

**Comment by Richard-Cao** [comment]
9.3我这边是没问题的，ios 10的问题我联系了react-native-wechat库的作者，他会来回复这个issue

**Comment by lilonghe** [comment]
O 谢谢啦 有什么需要我帮助的一定要联系我啊

**Comment by Richard-Cao** [comment]
好的，谢谢支持，我再催催wechat库的作者

**Comment by yorkie** [comment]
@lilonghe try with [this commands](https://github.com/AlexanderZaytsev/react-native-i18n/issues/29#issuecomment-234313522)

**Comment by Richard-Cao** [comment]
@yorkie 应该不是你发的这个issue的问题，这个issue里都是android的，他这个只是ios的，android是没问题的

**Comment by yorkie** [comment]
> @yorkie 应该不是你发的这个issue的问题，这个issue里都是android的，他这个只是ios的，android是没问题的

看我发的这个 issue 的 comment：

> here is how I solved this problem (by accident) for __Xcode 8__.

所以这个 commands 是用于解决 iOS10 的问题的，可以先请 @lilonghe 再试试吗？另外在项目中有没有使用其它的类似 native binding 这个的库，是否也存在类似的问题，麻烦帮忙追踪一下。

**Comment by Richard-Cao** [comment]
@yorkie 好的，其他的目前没上报出来这个问题

**Comment by lilonghe** [comment]
咳咳 .... 系统被我玩坏了....
文件都丢了 so.....

**Comment by ifcheung2012** [comment]
" undefined is not an object (evaluating 'WeChat.registerApp') ",额。。。。。。。 ，还没解决方案。。。。

**Comment by yorkie** [comment]
Android？

**Comment by yun0628** [comment]
ios 的  react-native-wechat 这个错到底怎么解决 单独写个 demo 没错 集成到 project 就一直报这个错  各位大哥大姐帮帮忙

**Comment by Richard-Cao** [comment]
@yun0628 你可以参照reading项目是如何接入的，或者直接去react-native-wechat项目看readme，或者加他们的群

**Comment by HHuiHao** [comment]
试试，进入项目根目录，命令：react-native start 如果不能启动, 提示端口被占用
解决方法：
1.查看占用端口的进程：lsof -i :8081 
2.杀死所有占用进程：kill -9 PID
3.重新启动：react-native start
4.xcode打开模拟器
