### ISSUE TITLE
Try to use navigator experimental based navigation solution

### ISSUE THREAD

**Issue by vmlinz** [attentiveness/reading#38]
NavigationExperimental based router and navigation methods can be driven by declarative way of changing the routes instead of directly accessing the navigation state by pushing and poping.

In short, solutions like **react-native-router-flux** and **ex-navigation** can simplify the navigation logic just like we use redux to simplify the application state.

Let's try to learn and understand these solutions and try to integrate them into this project.

**Comment by lakeoffaith** [comment]
+1

**Comment by Richard-Cao** [comment]
I will try. Thx~~

**Comment by phpsmarter** [comment]
Currently,which component is the best navigator for redux method?

**Comment by Richard-Cao** [comment]
@phpsmarter Maybe **react-native-router-flux**

**Comment by phpsmarter** [comment]
When I learn rn code ,I read a lot about redux-frame work.iReading App is a excellent work.But I thought still have some questions.Firstly,in component,still have some functions to proceed logic,especially
in didMount. I thought this is a init process,so can not find a good place to perform function. But when I read redux-saga examples:Async.I find  Async  has a code in the saga ,`yield fork(startup)`,you can learn about this code meaning from it's name. I thought all props including function must be injected  from  container,but I can find a way about init's function.Async's method maybe it is a good way.

**Comment by Richard-Cao** [comment]
Now reading used `redux-saga` instead of `redux-thunk`, I will learn more about `redux-saga`.

**Comment by Richard-Cao** [comment]
reading use `react-native-router-flux` now.

**Comment by vmlinz** [comment]
Awesome job
