### ISSUE TITLE
Execution failed for task ':RCTWeChat:extractReleaseAnnotations'. > com/intellij/psi/PsiJavaFile

### ISSUE THREAD

**Issue by GitSpring544** [attentiveness/reading#41]
你好，我使用的是windows 7，git clone了你的代码，npm install了相关依赖，一切正常，执行react-native run-android后编译失败，输入如下：
Incremental java compilation is an incubating feature.
:RCTWeChat:preBuild UP-TO-DATE
:RCTWeChat:preReleaseBuild UP-TO-DATE
:RCTWeChat:checkReleaseManifest
:RCTWeChat:preDebugAndroidTestBuild UP-TO-DATE
:RCTWeChat:preDebugBuild UP-TO-DATE
:RCTWeChat:preDebugUnitTestBuild UP-TO-DATE
:RCTWeChat:preReleaseUnitTestBuild UP-TO-DATE
:RCTWeChat:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:RCTWeChat:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:RCTWeChat:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:RCTWeChat:prepareComFacebookFrescoDrawee061Library UP-TO-DATE
:RCTWeChat:prepareComFacebookFrescoFbcore061Library UP-TO-DATE
:RCTWeChat:prepareComFacebookFrescoFresco061Library UP-TO-DATE
:RCTWeChat:prepareComFacebookFrescoImagepipeline061Library UP-TO-DATE
:RCTWeChat:prepareComFacebookFrescoImagepipelineOkhttp061Library UP-TO-DATE
:RCTWeChat:prepareComFacebookReactReactNative0153Library UP-TO-DATE
:RCTWeChat:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:RCTWeChat:prepareReleaseDependencies
:RCTWeChat:compileReleaseAidl UP-TO-DATE
:RCTWeChat:compileReleaseNdk UP-TO-DATE
:RCTWeChat:compileLint UP-TO-DATE
:RCTWeChat:copyReleaseLint UP-TO-DATE
:RCTWeChat:compileReleaseRenderscript UP-TO-DATE
:RCTWeChat:generateReleaseBuildConfig UP-TO-DATE
:RCTWeChat:generateReleaseResValues UP-TO-DATE
:RCTWeChat:generateReleaseResources UP-TO-DATE
:RCTWeChat:mergeReleaseResources UP-TO-DATE
:RCTWeChat:processReleaseManifest UP-TO-DATE
:RCTWeChat:processReleaseResources UP-TO-DATE
:RCTWeChat:generateReleaseSources UP-TO-DATE
:RCTWeChat:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:RCTWeChat:compileReleaseJavaWithJavac UP-TO-DATE
:RCTWeChat:extractReleaseAnnotations FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':RCTWeChat:extractReleaseAnnotations'.
  > com/intellij/psi/PsiJavaFile

**Comment by Richard-Cao** [comment]
这个貌似你ide的问题哦，com/intellij……

**Comment by GitSpring544** [comment]
IDE哪里有问题呢，我都可以运行其他网上的项目。你的这个项目服务起来之后浏览器里输入http://localhost:8081/index.android.bundle?platform=android也是可以的，你的开发环境是Windows的还是mac的

**Comment by Richard-Cao** [comment]
mac，你的报错信息显示你的intellij报错了

**Comment by worthywx** [comment]
可能是６４位系统缺少３２位兼容库，试试apt install gcc-multilib lib32z1 lib32stdc++6
