### ISSUE TITLE
requiring known module -WIN10

### ISSUE THREAD

**Issue by oppqw** [attentiveness/reading#42]
你好，我再win10启动的工程，部署到手机上后，手机加载完bundle后出现了requiring known module ”./qiniu/auth/digest.js”.If you are sure the module is there, try restarting the packager or running npm install 的异常，但是工程中已经存在了qiniu的module，且npm清空缓存都没用，您知道是为什么么？

**Comment by Richard-Cao** [comment]
这是因为用了leancloud的缘故，查看 #8 
解决方案是一样的
