### ISSUE TITLE
运行react-native run-android的时候报错

### ISSUE THREAD

**Issue by singlemonkey** [attentiveness/reading#43]
* What went wrong:                                                                       
A problem occurred configuring project ':app'.                                           
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.             
> Could not find any matches for com.tencent.bugly:crashreport:latest.release as no versions of com.tencent.bugly:crashreport are available.                                   
     Required by:                                                                        
         reading:app:unspecified

**Comment by Richard-Cao** [comment]
这是腾讯bugly的一个问题，可以暂时性先这样解决：http://bugly.qq.com/bbs/forum.php?mod=viewthread&tid=677

**Comment by singlemonkey** [comment]
这个答案在哪块儿了  链接只能到首页
