### ISSUE TITLE
#import "RCTBundleURLProvider.h" file not found 找不到这个文件

### ISSUE THREAD

**Issue by bubyday** [attentiveness/reading#45]
#import "RCTBundleURLProvider.h"
#import "RCTBundleURLProvider.h" file not found 找不到这个文件

这个问题怎么解决呢？ 是不是版本不同所产生的问题

**Comment by Richard-Cao** [comment]
我试了下，我这边没这个问题……要不你删了node_modules再重新npm install？顺便删下npm缓存

**Comment by geogie** [comment]
我也遇到"RCTBundleURLProvider.h" file not found这个问题了，不知道你们怎么解决的？

**Comment by geogie** [comment]
或者你们运行成功的环境版本能号发下吗？？

**Comment by Richard-Cao** [comment]
node：6.9.1
npm：3.10.x

**Comment by bubyday** [comment]
恩  确实需要执行这个操作node_modules再重新npm install

**Comment by Richard-Cao** [comment]
@bubyday 已经解决了？

**Comment by geogie** [comment]
@Richard-Cao 解决了吗？

**Comment by Richard-Cao** [comment]
@geogie 我这边没这个问题，你试试删了node_modules再重新npm install吧，应该没问题的

**Comment by youngcao2015** [comment]
execute  “react-native upgrade” command in your project directory.

**Comment by andlef** [comment]
http://anhj101.blog.163.com/blog/static/7674240520178501114591/

$ nvm deactivate
$ nvm ls
$ nvm uninstall [node-version]
$ find [node软连接、node及node_module文件及文件夹]
$ rm [删除上条一cmd找到的]

# 当前react-native最新版本0.48.1，默认创建时如不指定之前的（0.44.3）版本号，会有兼容性错错误
$ react-native init MyRNDemo --version 0.44.3  #ok

**Comment by Richard-Cao** [comment]
啥兼容性错误。目前reading工程里的版本是0.47.1，不需要降级到0.44.3，而且就算升级到0.48我想也不需要降级到0.44.3的，这不是一个好方法。
