### ISSUE TITLE
一直停留在启动页面，不知道问什么

### ISSUE THREAD

**Issue by zgxzgxzg** [attentiveness/reading#47]
环境配置好了之后，运行，react-native run-android ,下载成功，但是手机一直停留在启动页面，进不去
。
![device-2016-11-23-175246](https://cloud.githubusercontent.com/assets/13228580/20557305/ef285e40-b1a5-11e6-9922-a6cec15bdfcb.png)

**Comment by Richard-Cao** [comment]
debug一下看看有没有报错日志。

**Comment by zgxzgxzg** [comment]
怎么看？


2016-11-23 

15876500359 



发件人：Richard-Cao <notifications@github.com>
发送时间：2016-11-23 20:43
主题：Re: [attentiveness/reading] 一直停留在启动页面，不知道问什么 (#47)
收件人："attentiveness/reading"<reading@noreply.github.com>
抄送："zhangguoxiang"<15876500359@163.com>,"Author"<author@noreply.github.com>

debug一下看看有没有报错日志。

**Comment by zgxzgxzg** [comment]
怎么debug

**Comment by zgxzgxzg** [comment]
![device-2016-11-23-175246](https://cloud.githubusercontent.com/assets/13228580/20562663/b91cdbb8-b1bf-11e6-8149-bd757f2ddcf1.png)

**Comment by zgxzgxzg** [comment]
![image_20161123210010](https://cloud.githubusercontent.com/assets/13228580/20562679/d133eeda-b1bf-11e6-9a5a-38171b3ccdbf.png)

**Comment by zgxzgxzg** [comment]
摇一摇手机没有反应,  配置界面不出来

**Comment by Richard-Cao** [comment]
关于debug可以看[Debugging](http://facebook.github.io/react-native/docs/debugging.html)，摇一摇无法出现配置界面，点击菜单键也可以。如果是小米或者魅族的部分手机，需要打开应用的悬浮窗权限。

**Comment by zgxzgxzg** [comment]
解决了，可以关闭问题了

**Comment by zgxzgxzg** [comment]
![image_20161124103005](https://cloud.githubusercontent.com/assets/13228580/20584778/e84c6568-b230-11e6-8088-2d40e7f3e1a1.png)

**Comment by zgxzgxzg** [comment]
上面这个menu，在android代码里面怎么启动？
