### ISSUE TITLE
menu，在android代码里面怎么启动？

### ISSUE THREAD

**Issue by zgxzgxzg** [attentiveness/reading#48]
![image_20161124103005](https://cloud.githubusercontent.com/assets/13228580/20584927/048b01a2-b232-11e6-95e5-28d7639cc82c.png)

摇一摇没效果，因为是把react移植到自己的原生项目中...

**Comment by Richard-Cao** [comment]
一样有效果，自己按照rn的工程配置一下就行了，看下官方文档吧，讲的很清楚了。
