### ISSUE TITLE
TaskQueue: Error with task : undefined is not an object (evaluating 'DrawerLayoutAndroid.positions.Left')

### ISSUE THREAD

**Issue by gp5251** [attentiveness/reading#5]
进入app后报错，请看看这是什么问题？
TaskQueue: Error with task : undefined is not an object (evaluating 'DrawerLayoutAndroid.positions.Left')

**Comment by Richard-Cao** [comment]
因为DrawerLayoutAndroid控件不支持ios，你应该是跑的ios
