### ISSUE TITLE
遇到了一个问题，请教一下

### ISSUE THREAD

**Issue by zuijiaoluo** [attentiveness/reading#51]
TransformError: /Users/xxx/Desktop/git/reading/node_modules/debug/browser.js: Couldn't find preset "es2015" relative to directory "/Users/xxx/Desktop/git/reading/node_modules/debug"

RCTFatal
-[RCTBatchedBridge stopLoadingWithError:]
__25-[RCTBatchedBridge start]_block_invoke_2
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start

**Comment by zuijiaoluo** [comment]
我设置了.babelrc    但是还是出错    

Unhandled JS Exception: TypeError

assign
    index.ios.bundle?platform=ios&dev=true&minify=false:327:64
defineProperty
    index.ios.bundle?platform=ios&dev=true&minify=false:30618:61
loadModuleImplementation
    index.ios.bundle?platform=ios&dev=true&minify=false:188:8
guardedLoadModule
    index.ios.bundle?platform=ios&dev=true&minify=false:133:37
global code
    index.ios.bundle?platform=ios&dev=true&minify=false:108999:9

**Comment by pitatensai** [comment]
@zuijiaoluo 试下 添加babel-preset-es2015 我加了以后就正常了
`npm install babel-preset-es2015 --save-dev`
