### ISSUE TITLE
RCTWeChat.xcodeproj下search header paths改了没用

### ISSUE THREAD

**Issue by johnzhu12** [attentiveness/reading#56]
我也是运行ios报错 RCTBridgeModule.h这个头文件没找到，看到你说的RCTWebChat.xcodeproj的build setting 下改，改完以后还是报找不到，
$(SRCROOT)/../../react-native/React
$(SRCROOT)/../../react-native/Libraries
这样两个一个是加在header search path 
一个是加在library search path 下，对吧，要选recursive么

**Comment by johnzhu12** [comment]
哦，找到了，别理我

**Comment by johnzhu12** [comment]
React/RCTEventEmitter.h 照着那个在header search paths 改了，现在报React/RCTEventEmitter.h 文件找不到

**Comment by johnzhu12** [comment]
![1](https://cloud.githubusercontent.com/assets/11485619/22180657/ac3deaec-e0b1-11e6-8f7a-c9021bdc2765.png)

已经照着改了，还是报RCTBridgeModule.h file not found

**Comment by johnzhu12** [comment]
两个都加search header paths下，又报code push下的React/RCTEventEmitter.h找不到

![1](https://cloud.githubusercontent.com/assets/11485619/22180751/5c4ac728-e0b4-11e6-809b-a99e0d1092d1.png)

**Comment by Richard-Cao** [comment]
。。这个就是搜索路径的问题，你可以去react-native-wechat库看看

**Comment by johnzhu12** [comment]
![1](https://cloud.githubusercontent.com/assets/11485619/22181003/d4ddb7ec-e0bc-11e6-9223-c8c90f8c0a83.png)
![2](https://cloud.githubusercontent.com/assets/11485619/22181005/d635479a-e0bc-11e6-8e23-8bd93d6b5aab.png)
![3](https://cloud.githubusercontent.com/assets/11485619/22180997/b09b2a22-e0bc-11e6-907d-b38a92d5f0e4.png)

帮我看看上面的图片，nodemodule下路径就两层，所以看你的回答是 $(SRCROOT)/../../  ，但在build setting下$(SRCROOT)好像有1.8.0的版本目录在里面，是要 ../../../../去找么，所以我改成$(SRCROOT)/../../../../react-native/0.39.2/react-native/React ，不过好像还是没用，xcode的一些配置不懂，麻烦指导下，谢谢

**Comment by johnzhu12** [comment]
/Users/zhujohn/Desktop/RN/reading-master/node_modules/.npminstall/react-native/0.39.2/react-native/React/Base
 我是在这下面看到RCTBridgeModule.h等等头文件

**Comment by johnzhu12** [comment]
现在编译通过了，总共有三个头文件找不到，我就按照上面的加了，不知道对不对，还出现一个case 未定义，我就注释掉了
//    case UIUserInterfaceIdiomCarPlay:
//      return @"carplay";
不知道怎么弄，感觉哪里不多，先通过编译吧，谢谢啦

**Comment by johnzhu12** [comment]
应该搞得不对，下图出现了

![1](https://cloud.githubusercontent.com/assets/11485619/22181178/2cc9602e-e0c1-11e6-87b2-417ff20dbc8e.png)

**Comment by Richard-Cao** [comment]
你改混乱了……

**Comment by johnzhu12** [comment]
那按着一开始的做法，编译不通过，
$(SRCROOT)/../../react-native/React
$(SRCROOT)/../../react-native/Libraries
加这些在search header paths里

**Comment by Richard-Cao** [comment]
你看下react-native-wechat这个仓库1.8.0的配置吧

**Comment by johnzhu12** [comment]
好的

**Comment by johnzhu12** [comment]
ok,I have found the reason,cnpm 安装的目录结构和npm不一致导致的，cnmp都是软链接。thanks for the patience,i will close this issue!

**Comment by Richard-Cao** [comment]
原来是这个问题，thanks
