### ISSUE TITLE
获取分类时，提示“网路发生错误，请重试"

### ISSUE THREAD

**Issue by totothink** [attentiveness/reading#57]
从AppStore安装了iReading，启动后选择分类时，提示“网路发生错误，请重试”

**Comment by johnzhu12** [comment]
我在xcode里运行时也是，
`try {
    yield put(fetchTypeList());
    const typeList = yield call(request, WEXIN_ARTICLE_TYPE, 'get');
    yield put(receiveTypeList(typeList.showapi_res_body.typeList));
    yield call(store.save, 'typeList', typeList.showapi_res_body.typeList);
    const errorMessage = typeList.showapi_res_error;
    if (errorMessage && errorMessage !== '') {
      yield toastShort(errorMessage);
    }
  } catch (error) {
    yield put(receiveTypeList([]));
    yield toastShort('网络发生错误，请重试');
  }`

所以是啥请求没完成么

**Comment by totothink** [comment]
@johnzhu12 @Richard-Cao 说是百度API的问题，目前还没办法解决。

**Comment by Richard-Cao** [comment]
对的，这个后端的问题，百度apistore的问题

**Comment by Richard-Cao** [comment]
已经可用了
