### ISSUE TITLE
baidu api不能用了？

### ISSUE THREAD

**Issue by ddvkid** [attentiveness/reading#58]
导致app打不开啊

**Comment by Richard-Cao** [comment]
那个api不是不能用，是不太稳定了，多刷几次才能刷到。

**Comment by ddvkid** [comment]
那悲了个剧，我刷了很多次都不行，可能国外完全刷不出来。有没有考虑换个api？或者做一些mock-data我们好学习用。否则完全打不开呀

**Comment by Richard-Cao** [comment]
有考虑换api，不过最近有点忙，等稍微闲一点我就换个api

**Comment by Richard-Cao** [comment]
已经可用了
