### ISSUE TITLE
ios运行后出现如下错误，麻烦帮忙看下是什么问题，谢谢；

### ISSUE THREAD

**Issue by huaganshang** [attentiveness/reading#6]
![qq20160320-0 2x](https://cloud.githubusercontent.com/assets/2785115/13902744/863aebd2-ee91-11e5-9ce6-726ebffa4a55.png)

图片里怎么会有DrawerLayoutAndroid   安卓的字样呢？

**Comment by Richard-Cao** [comment]
因为我还没兼容ios，等react-native 0.22 release之后我就开始兼容ios

**Comment by huaganshang** [comment]
期待。。。

**Comment by GloomHu** [comment]
我也遇到了。。求解决方法

**Comment by Richard-Cao** [comment]
@GloomHu 这是因为我还没兼容ios，兼容之后就好啦，目前发现0.22.2还是不太完善，等0.23release之后我就开始兼容

**Comment by Richard-Cao** [comment]
ios已兼容

**Comment by bluesea** [comment]
我这最新版本，怎么还是报这个错误- -
