### ISSUE TITLE
React/RCTBridgeModule.h'file not found

### ISSUE THREAD

**Issue by BenJChen** [attentiveness/reading#62]
When I run this project, prompt 'React/RCTBridgeModule.h'file not found', how to solve the problem

**Comment by Richard-Cao** [comment]
what is your react-native version?

**Comment by BenJChen** [comment]
I tried version 0.39 and 0.40

**Comment by BenJChen** [comment]
It seems npm download package can not read in the project, whether you need to set the dependency, if necessary, how to operate

**Comment by Richard-Cao** [comment]
0.39 is right, didn't support 0.40.
just run `npm install`.

**Comment by zhuangchuming** [comment]
@Richard-Cao I have same problem ,i don't know how to fix it.when i try to run npm install.it tips me :npm WARN react-native-wechat@1.9.0 requires a peer of react-native@>=0.40 but none was installed.

**Comment by BenJChen** [comment]
@Richard-Cao  In the 0.39 version, it also has the same error

**Comment by BenJChen** [comment]
@Richard-Cao  ![image](https://cloud.githubusercontent.com/assets/15866873/23390868/9e0664ba-fdab-11e6-9fef-ec11afe6005e.png)

**Comment by Richard-Cao** [comment]
What is your `react-native-wechat` sdk version?

**Comment by sysoft** [comment]
package.json
----------------
"dependecies": {
  ....
  "react-native-wechat": "~1.8.0"
  ....
}

**Comment by Richard-Cao** [comment]
i think you installed not 1.8.0.

please check: https://github.com/weflex/react-native-wechat/issues/174

maybe try: `npm install react-native-wechat@1.8.0 --save`

**Comment by Richard-Cao** [comment]
upgrade to react-native 0.42.3 now
