### ISSUE TITLE
 Could not expand ZIP

### ISSUE THREAD

**Issue by AlphaDu** [attentiveness/reading#63]
* What went wrong:
Execution failed for task ':react-native-code-push:prepareComAndroidSupportSupportV42321Library'.
> Could not expand ZIP 'D:\Android\sdk\extras\android\m2repository\com\android\support\support-v4\23.2.1\support-v4-23.2.1.aar'.
![default](https://cloud.githubusercontent.com/assets/24519784/23391883/09e1aada-fdb3-11e6-84d2-154cc2ba38e8.png)

**Comment by Richard-Cao** [comment]
maybe your android sdk have problems

**Comment by czhaoli** [comment]
i think so
