### ISSUE TITLE
网络发生错误,请重试

### ISSUE THREAD

**Issue by ysq1051838264** [attentiveness/reading#64]
日志详情：
03-06 20:45:29.177 22829-24872/com.reading I/System: core_booster, getBoosterConfig = false
03-06 20:45:29.217 22829-23582/com.reading I/ReactNativeJS: action @ 20:45:29.231 REQUEST_TYPE_LIST
03-06 20:45:29.227 22829-23582/com.reading I/ReactNativeJS: '%c prev state', 'color: #9E9E9E; font-weight: bold', { routes: 
                                                               { scene: 
                                                                  { getSceneStyle: [Function: getSceneStyle],
                                                                    navigationBarStyle: 103,
                                                                    titleStyle: 104,
                                                                    backButtonImage: 7,
                                                                    dispatch: [Function],
                                                                    key: 'initCategory_0_initCategory',
                                                                    name: 'initCategory',
                                                                    sceneKey: 'initCategory',
                                                                    parent: 'root',
                                                                    type: 'REACT_NATIVE_ROUTER_FLUX_REPLACE',
                                                                    hideNavBar: true,
                                                                    hideTabBar: true,
                                                                    component: 
                                                                     { [Function: Connect]
                                                                       WrappedComponent: [Function: CategoryContainer],
                                                                       displayName: 'Connect(CategoryContainer)',
                                                                       childContextTypes: { storeSubscription: { [Function: checkType] isRequired: [Function: checkType] } },
                                                                       contextTypes: 
                                                                        { store: { [Function: checkType] isRequired: [Function: checkType] },
                                                                          storeSubscription: { [Function: checkType] isRequired: [Function: checkType] } },
                                                                       propTypes: 
                                                                        { store: { [Function: checkType] isRequired: [Function: checkType] },
                                                                          storeSubscription: { [Function: checkType] isRequired: [Function: checkType] } } },
                                                                    index: 0,
                                                                    isFirst: true } },
                                                              read: 
                                                               { isRefreshing: false,
                                                                 loading: false,
                                                                 isLoadMore: false,
                                                                 noMore: false,
                                                                 articleList: {} },
                                                              category: { loading: false, typeList: [] } }
03-06 20:45:29.227 22829-23582/com.reading I/ReactNativeJS: '%c action', 'color: #03A9F4; font-weight: bold', { type: 'REQUEST_TYPE_LIST' }
03-06 20:45:29.227 22829-23582/com.reading I/ReactNativeJS: '%c next state', 'color: #4CAF50; font-weight: bold', { routes: 
                                                               { scene: 
                                                                  { getSceneStyle: [Function: getSceneStyle],
                                                                    navigationBarStyle: 103,
                                                                    titleStyle: 104,
                                                                    backButtonImage: 7,
                                                                    dispatch: [Function],
                                                                    key: 'initCategory_0_initCategory',
                                                                    name: 'initCategory',
                                                                    sceneKey: 'initCategory',
                                                                    parent: 'root',
                                                                    type: 'REACT_NATIVE_ROUTER_FLUX_REPLACE',
                                                                    hideNavBar: true,
                                                                    hideTabBar: true,
                                                                    component: 
                                                                     { [Function: Connect]
                                                                       WrappedComponent: [Function: CategoryContainer],
                                                                       displayName: 'Connect(CategoryContainer)',
                                                                       childContextTypes: { storeSubscription: { [Function: checkType] isRequired: [Function: checkType] } },
                                                                       contextTypes: 
                                                                        { store: { [Function: checkType] isRequired: [Function: checkType] },
                                                                          storeSubscription: { [Function: checkType] isRequired: [Function: checkType] } },
                                                                       propTypes: 
                                                                        { store: { [Function: checkType] isRequired: [Function: checkType] },
                                                                          storeSubscription: { [Function: checkType] isRequired: [Function: checkType] } } },
                                                                    index: 0,
                                                                    isFirst: true } },
                                                              read: 
                                                               { isRefreshing: false,
                                                                 loading: false,
                                                                 isLoadMore: false,
                                                                 noMore: false,
                                                                 articleList: {} },
                                                              category: { loading: false, typeList: [] } }
03-06 20:45:29.227 22829-23582/com.reading I/ReactNativeJS: —— log end ——
03-06 20:45:29.237 22829-23582/com.reading I/ReactNativeJS: action @ 20:45:29.242 FETCH_TYPE_LIST
03-06 20:45:29.237 22829-23582/com.reading I/ReactNativeJS: '%c prev state', 'color: #9E9E9E; font-weight: bold', { routes: 
                                                               { scene: 
                                                                  { getSceneStyle: [Function: getSceneStyle],
                                                                    navigationBarStyle: 103,
                                                                    titleStyle: 104,
                                                                    backButtonImage: 7,
                                                                    dispatch: [Function],
                                                                    key: 'initCategory_0_initCategory',
                                                                    name: 'initCategory',
                                                                    sceneKey: 'initCategory',
                                                                    parent: 'root',
                                                                    type: 'REACT_NATIVE_ROUTER_FLUX_REPLACE',
                                                                    hideNavBar: true,
                                                                    hideTabBar: true,
                                                                    component: 
                                                                     { [Function: Connect]
                                                                       WrappedComponent: [Function: CategoryContainer],
                                                                       displayName: 'Connect(CategoryContainer)',
                                                                       childContextTypes: { storeSubscription: { [Function: checkType] isRequired: [Function: checkType] } },
                                                                       contextTypes: 
                                                                        { store: { [Function: checkType] isRequired: [Function: checkType] },
                                                                          storeSubscription: { [Function: checkType] isRequired: [Function: checkType] } },
                                                                       propTypes: 
                                                                        { store: { [Function: checkType] isRequired: [Function: checkType] },
                                                                          storeSubscription: { [Function: checkType] isRequired: [Function: checkType] } } },
                                                                    index: 0,
                                                                    isFirst: true } },
                                                              read: 
                                                               { isRefreshing: false,
                                                                 loading: false,
                                                                 isLoadMore: false,
                                                                 noMore: false,
                                                                 articleList: {} },
                                                              category: { loading: false, typeList: [] } }
03-06 20:45:29.237 22829-23582/com.reading I/ReactNativeJS: '%c action', 'color: #03A9F4; font-weight: bold', { type: 'FETCH_TYPE_LIST' }
03-06 20:45:29.247 22829-23582/com.reading I/ReactNativeJS: '%c next state', 'color: #4CAF50; font-weight: bold', { routes: 
                                                               { scene: 
                                                                  { getSceneStyle: [Function: getSceneStyle],
                                                                    navigationBarStyle: 103,
                                                                    titleStyle: 104,
                                                                    backButtonImage: 7,
                                                                    dispatch: [Function],
                                                                    key: 'initCategory_0_initCategory',
                                                                    name: 'initCategory',
                                                                    sceneKey: 'initCategory',
                                                                    parent: 'root',
                                                                    type: 'REACT_NATIVE_ROUTER_FLUX_REPLACE',
                                                                    hideNavBar: true,
                                                                    hideTabBar: true,
                                                                    component: 
                                                                     { [Function: Connect]
                                                                       WrappedComponent: [Function: CategoryContainer],
                                                                       displayName: 'Connect(CategoryContainer)',
                                                                       childContextTypes: { storeSubscription: { [Function: checkType] isRequired: [Function: checkType] } },
                                                                       contextTypes: 
                                                                        { store: { [Function: checkType] isRequired: [Function: checkType] },
                                                                          storeSubscription: { [Function: checkType] isRequired: [Function: checkType] } },
                                                                       propTypes: 
                                                                        { store: { [Function: checkType] isRequired: [Function: checkType] },
                                                                          storeSubscription: { [Function: checkType] isRequired: [Function: checkType] } } },
                                                                    index: 0,
                                                                    isFirst: true } },
                                                              read: 
                                                               { isRefreshing: false,
                                                                 loading: false,
                                                                 isLoadMore: false,
                                                                 noMore: false,
                                                                 articleList: {} },
                                                              category: { loading: true, typeList: [] } }
03-06 20:45:29.247 22829-23582/com.reading I/ReactNativeJS: —— log end ——
03-06 20:45:29.267 22829-23632/com.reading I/System: core_booster, getBoosterConfig = false
03-06 20:45:29.457 22829-23582/com.reading I/ReactNativeJS: action @ 20:45:29.392 RECEIVE_TYPE_LIST
03-06 20:45:29.457 22829-23582/com.reading I/ReactNativeJS: '%c prev state', 'color: #9E9E9E; font-weight: bold', { routes: 
                                                               { scene: 
                                                                  { getSceneStyle: [Function: getSceneStyle],
                                                                    navigationBarStyle: 103,
                                                                    titleStyle: 104,
                                                                    backButtonImage: 7,
                                                                    dispatch: [Function],
                                                                    key: 'initCategory_0_initCategory',
                                                                    name: 'initCategory',
                                                                    sceneKey: 'initCategory',
                                                                    parent: 'root',
                                                                    type: 'REACT_NATIVE_ROUTER_FLUX_REPLACE',
                                                                    hideNavBar: true,
                                                                    hideTabBar: true,
                                                                    component: 
                                                                     { [Function: Connect]
                                                                       WrappedComponent: [Function: CategoryContainer],
                                                                       displayName: 'Connect(CategoryContainer)',
                                                                       childContextTypes: { storeSubscription: { [Function: checkType] isRequired: [Function: checkType] } },
                                                                       contextTypes: 
                                                                        { store: { [Function: checkType] isRequired: [Function: checkType] },
                                                                          storeSubscription: { [Function: checkType] isRequired: [Function: checkType] } },
                                                                       propTypes: 
                                                                        { store: { [Function: checkType] isRequired: [Function: checkType] },
                                                                          storeSubscription: { [Function: checkType] isRequired: [Function: checkType] } } },
                                                                    index: 0,
                                                                    isFirst: true } },
                                                              read: 
                                                               { isRefreshing: false,
                                                                 loading: false,
                                                                 isLoadMore: false,
                                                                 noMore: false,
                                                                 articleList: {} },
                                                              category: { loading: true, typeList: [] } }
03-06 20:45:29.457 22829-23582/com.reading I/ReactNativeJS: '%c action', 'color: #03A9F4; font-weight: bold', { type: 'RECEIVE_TYPE_LIST', typeList: [] }
03-06 20:45:29.467 22829-23582/com.reading I/ReactNativeJS: '%c next state', 'color: #4CAF50; font-weight: bold', { routes: 
                                                               { scene: 
                                                                  { getSceneStyle: [Function: getSceneStyle],
                                                                    navigationBarStyle: 103,
                                                                    titleStyle: 104,
                                                                    backButtonImage: 7,
                                                                    dispatch: [Function],
                                                                    key: 'initCategory_0_initCategory',
                                                                    name: 'initCategory',
                                                                    sceneKey: 'initCategory',
                                                                    parent: 'root',
                                                                    type: 'REACT_NATIVE_ROUTER_FLUX_REPLACE',
                                                                    hideNavBar: true,
                                                                    hideTabBar: true,
                                                                    component: 
                                                                     { [Function: Connect]
                                                                       WrappedComponent: [Function: CategoryContainer],
                                                                       displayName: 'Connect(CategoryContainer)',
                                                                       childContextTypes: { storeSubscription: { [Function: checkType] isRequired: [Function: checkType] } },
                                                                       contextTypes: 
                                                                        { store: { [Function: checkType] isRequired: [Function: checkType] },
                                                                          storeSubscription: { [Function: checkType] isRequired: [Function: checkType] } },
                                                                       propTypes: 
                                                                        { store: { [Function: checkType] isRequired: [Function: checkType] },
                                                                          storeSubscription: { [Function: checkType] isRequired: [Function: checkType] } } },
                                                                    index: 0,
                                                                    isFirst: true } },
                                                              read: 
                                                               { isRefreshing: false,
                                                                 loading: false,
                                                                 isLoadMore: false,
                                                                 noMore: false,
                                                                 articleList: {} },
                                                              category: { loading: false, typeList: [] } }
03-06 20:45:29.467 22829-23582/com.reading I/ReactNativeJS: —— log end ——
03-06 20:45:31.207 22829-24905/com.reading I/System: core_booster, getBoosterConfig = false
03-06 20:45:33.227 22829-24939/com.reading I/System: core_booster, getBoosterConfig = false

**Comment by Richard-Cao** [comment]
看下 #61
