### ISSUE TITLE
无法调试

### ISSUE THREAD

**Issue by johnzhu12** [attentiveness/reading#65]
首先非常感谢作者，正在模仿作者的东西，写一个公司的项目

![h](https://cloud.githubusercontent.com/assets/11485619/23734149/070b6ed4-04b8-11e7-963e-bb865ef7fe8e.png)

初学者问两个问题，1个是如图的ajax请求，咋network抓取不到
2是我在下图的代码位置没法打断点，我要看请求完的数据，只能console打出来么？

![t](https://cloud.githubusercontent.com/assets/11485619/23734208/86eb9aca-04b8-11e7-83a8-875d7f8752f8.png)

**Comment by johnzhu12** [comment]
包括下面的 error条件下也没法打断点，加入debugger;也没用

**Comment by johnzhu12** [comment]
哦，所以都只能在console下看logger打出的状态变化，对吧

**Comment by Richard-Cao** [comment]
目前百度的api这个被废弃掉了，所以暂时没有数据，最近我比较忙，忙完了我会重新找API重构项目

**Comment by Richard-Cao** [comment]
API完成
