### ISSUE TITLE
react-native run-ios 报错

### ISSUE THREAD

**Issue by eightJie** [attentiveness/reading#68]
作者你好，很高兴你还在维护这个项目！
我更新最新代码，启动时报如下错误：
=== BUILD TARGET yoga OF PROJECT React WITH CONFIGURATION Debug ===

Check dependencies

PBXCp /Users/xcoder/Desktop/react-native/reading/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.h /Users/xcoder/Desktop/react-native/reading/ios/build/Build/Products/Debug-iphonesimulator/include/yoga/Yoga.h
    cd /Users/xcoder/Desktop/react-native/reading/node_modules/react-native/React
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/xcoder/Library/Android/sdk/tools:/Users/xcoder/Library/Android/sdk/platform-tools"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/xcoder/Desktop/react-native/reading/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.h /Users/xcoder/Desktop/react-native/reading/ios/build/Build/Products/Debug-iphonesimulator/include/yoga
error: couldn't create directory /Users/xcoder/Desktop/react-native/reading/ios/build/Build/Products/Debug-iphonesimulator/include/yoga: Permission denied

error: open /Users/xcoder/Desktop/react-native/reading/ios/build/Build/Products/Debug-iphonesimulator/include/yoga/Yoga.h: No such file or directory

PBXCp /Users/xcoder/Desktop/react-native/reading/node_modules/react-native/ReactCommon/yoga/yoga/YGEnums.h /Users/xcoder/Desktop/react-native/reading/ios/build/Build/Products/Debug-iphonesimulator/include/yoga/YGEnums.h
    cd /Users/xcoder/Desktop/react-native/reading/node_modules/react-native/React
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/xcoder/Library/Android/sdk/tools:/Users/xcoder/Library/Android/sdk/platform-tools"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/xcoder/Desktop/react-native/reading/node_modules/react-native/ReactCommon/yoga/yoga/YGEnums.h /Users/xcoder/Desktop/react-native/reading/ios/build/Build/Products/Debug-iphonesimulator/include/yoga
error: couldn't create directory /Users/xcoder/Desktop/react-native/reading/ios/build/Build/Products/Debug-iphonesimulator/include/yoga: Permission deniederror: open /Users/xcoder/Desktop/react-native/reading/ios/build/Build/Products/Debug-iphonesimulator/include/yoga/YGEnums.h: No such file or directory

PBXCp /Users/xcoder/Desktop/react-native/reading/node_modules/react-native/ReactCommon/yoga/yoga/YGMacros.h /Users/xcoder/Desktop/react-native/reading/ios/build/Build/Products/Debug-iphonesimulator/include/yoga/YGMacros.h
    cd /Users/xcoder/Desktop/react-native/reading/node_modules/react-native/React
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/xcoder/Library/Android/sdk/tools:/Users/xcoder/Library/Android/sdk/platform-tools"
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /Users/xcoder/Desktop/react-native/reading/node_modules/react-native/ReactCommon/yoga/yoga/YGMacros.h /Users/xcoder/Desktop/react-native/reading/ios/build/Build/Products/Debug-iphonesimulator/include/yoga
error: couldn't create directory /Users/xcoder/Desktop/react-native/reading/ios/build/Build/Products/Debug-iphonesimulator/include/yoga: Permission deniederror: open /Users/xcoder/Desktop/react-native/reading/ios/build/Build/Products/Debug-iphonesimulator/include/yoga/YGMacros.h: No such file or directory

** BUILD FAILED **

The following build commands failed:
	PBXCp /Users/xcoder/Desktop/react-native/reading/node_modules/react-native/ReactCommon/yoga/yoga/YGEnums.h /Users/xcoder/Desktop/react-native/reading/ios/build/Build/Products/Debug-iphonesimulator/include/yoga/YGEnums.h
	PBXCp /Users/xcoder/Desktop/react-native/reading/node_modules/react-native/ReactCommon/yoga/yoga/YGMacros.h /Users/xcoder/Desktop/react-native/reading/ios/build/Build/Products/Debug-iphonesimulator/include/yoga/YGMacros.h

帮我看一下，谢谢！

环境：
react-native-cli: 2.0.1
react-native: 0.41.2
node：v5.5.0

**Comment by Richard-Cao** [comment]
<img width="840" alt="b7fb6ae5-f13e-42d9-9187-9e2b327205c5" src="https://cloud.githubusercontent.com/assets/5953992/24323028/5729aac6-11aa-11e7-82d4-72b21c138ad9.png">

这样设置试试看
