### ISSUE TITLE
Will be more helpful if there is some simple react native, redux examples

### ISSUE THREAD

**Issue by karthickvkumar** [attentiveness/reading#7]
Hi @Richard-Cao , Thank you for this awesome app. Im very new to react native so when i see this app, i feel little bit difficult to understand. If you find some time please add any simple react-native redux app using post and get data from local server. It would be more helpful to understand.

Thanks in Advance

**Comment by Richard-Cao** [comment]
Thanks！ @karthickvkumar Reading is a product-level open source project which uesd redux. If I find some time, I will write simple react-native redux app.

**Comment by karthickvkumar** [comment]
Thank you so much @Richard-Cao
