### ISSUE TITLE
[npm install]warn with react version

### ISSUE THREAD

**Issue by firetheworld** [attentiveness/reading#71]
Hi , I'm runing your project,and I got warn about react version when I excu 'npm install'
Here is WARN:
`npm WARN react-dom@15.5.4 requires a peer of react@^15.5.4 but none was installed.
npm WARN react-native@0.43.2 requires a peer of react@16.0.0-alpha.6 but none was installed.
npm WARN react-native-timeago@0.3.0 requires a peer of react@>=0.14.0 but none was installed.
npm WARN react-static-container@1.0.1 requires a peer of react@^0.13.0 || ^0.14.0 || ^15.0.0 but none was installed.
npm WARN redux-devtools@3.3.2 requires a peer of react@^0.14.0 || ^15.0.0 but none was installed.
`

**Comment by Richard-Cao** [comment]
`rm -rf node_modules` and `npm install` again.

please check `package.json`.

**Comment by Richard-Cao** [comment]
react-native 0.43 will install react `16.0.0-alpha.6`, those warning you can ignore temporary.
