### ISSUE TITLE
Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/reading.app/Info.plist

### ISSUE THREAD

**Issue by kala888** [attentiveness/reading#76]
it looks like some configuration issue when you changed the reading.app to iReading.app
![image](https://user-images.githubusercontent.com/1215976/27025372-d7ac36b2-4f8c-11e7-9fa1-f7f1566cd912.png)

**Comment by Richard-Cao** [comment]
Could you clean your project? 
I don't have this problem locally.

**Comment by caoyunxiao** [comment]
I met the same problem

**Comment by Richard-Cao** [comment]
Please clean your project and try again.

**Comment by wuyunqiang** [comment]
I met the same problem.

**Comment by Richard-Cao** [comment]
Please use `Xcode` build instead of `react-native run-ios`.

**Comment by Richard-Cao** [comment]
Now `react-native run-ios` is right.
Thank you!

**Comment by wuyunqiang** [comment]
good good da.
