### ISSUE TITLE
请问，提示找不到qiniu/io.js，怎么改，初学者，请见谅！

### ISSUE THREAD

**Issue by vncnetcat** [attentiveness/reading#8]
环境：windows7 android测试
![screenshot_2016-05-17-17-50-37](https://cloud.githubusercontent.com/assets/19406407/15318887/bbeae66e-1c5a-11e6-8de4-ae47147cc9b6.png)

**Comment by Richard-Cao** [comment]
升级node版本到4.x就可以了  你这是node版本太低

**Comment by Richard-Cao** [comment]
而且这个你应该重新npm install一下，我这里面并没有安装七牛的sdk，你这里报错提示的是七牛sdk

**Comment by Richard-Cao** [comment]
我知道什么情况了，是avoscloud-sdk的原因，需要回退一下avoscloud-sdk的版本

1. `npm uninstall avoscloud-sdk`

2.`npm install avoscloud-sdk@1.0.0-rc5`

即可

**Comment by fancyallen** [comment]
我也遇到了，1. npm uninstall avoscloud-sdk
2.npm install avoscloud-sdk@1.0.0-rc5

还是同样的问题
D:\project\React-Native-Project\reading>npm install avoscloud-sdk@1.0.0-rc5
reading@1.0.0-rc D:\project\React-Native-Project\reading
`-- avoscloud-sdk@1.0.0-rc5  extraneous
第二步出现这个信息是不是成功了？

**Comment by Richard-Cao** [comment]
准确的说，你拉最新的代码已经没有avoscloud-sdk这个东西了。。已经换成leancloud-storage了，就不存在这个问题了 @fancyallen

**Comment by Mr7Cat** [comment]
leancloud-storage 也有同样的问题，需要用哪个版本的，当前是1.3.3

**Comment by Richard-Cao** [comment]
@Mr7Cat 这问题只在win上有。好像win上都没兼容到，老版本我也不清楚哪个可以。。建议如果不看重feedback模块的话，可以删掉leancloud-storage ，然后把feedback里的相关代码注释掉

**Comment by codeHui** [comment]
@Richard-Cao 问下你是在用mac开发吗？我也有qiniu问题了，win7

**Comment by Richard-Cao** [comment]
@codeHui win下好像leancloud-storage这个库支持不好，把这个从package.json里删掉然后把feedback相关代码注释掉就行了

**Comment by woitaylor** [comment]
我把这个leancloud-storage这个库从根目录的packeage.json里面删除了，
FeedBack.js如下图注释：
![image](https://cloud.githubusercontent.com/assets/17422824/19219394/601da482-8e44-11e6-8510-ea64cc64708d.png)
报错如下：
![image](https://cloud.githubusercontent.com/assets/17422824/19219381/05421ade-8e44-11e6-9316-c7140e6d5b05.png)
如何解决？

**Comment by Richard-Cao** [comment]
@woitaylor 你光删除package.json里的没用啊。。。你要删除了这个之后用npm uninstall把node_modules里的这个库删除才是真正有用的……你应该先看看npm是如何工作的

**Comment by woitaylor** [comment]
@Richard-Cao 搞Android的刚接触这个，可是如果我在npm install之前把代码改了，把依赖删了，再npm install，不是一样的吗？

**Comment by Richard-Cao** [comment]
@woitaylor 是一样的，但是你要改了package.json之后，删掉node_modules然后重新npm install才行，因为你不是增加依赖，你是删除依赖，或者你用npm prune也行应该

**Comment by woitaylor** [comment]
@Richard-Cao 可是从你github上下载的包里面本来就没有node_modules这个文件夹，然后我修改package.json，然后再使用npm install。这个时候根目录下面才会有node_modules这个文件夹。所以我感觉原因不是这个。
我操作步骤：
1.按你说的进行修改package.json和feedback.js
2.npm install
3.react-native run-android(这个命令会自动开启另外一个窗口进行react-native start)

我的npm的版本npm -v ===>2.15.9

**Comment by Richard-Cao** [comment]
@woitaylor (⊙o⊙)…你的这个报错很明显，就是因为leancloud-storage的问题，如果你真的注释掉了也删掉了，根本不可能出现这个库，如何报错？很显然啊。
npm建议更新到3.x

**Comment by woitaylor** [comment]
@Richard-Cao 其实我也有点想不通，到时换个电脑试试，谢谢了。

**Comment by Richard-Cao** [comment]
升级下npm到3.x吧，2.x会有问题

**Comment by gnaykcin** [comment]
@woitaylor 问题解决啦？怎么解决的

**Comment by Jeffreyli1983** [comment]
搜索一下leancloud-storage，发现import AV from 'leancloud-storage' 文件后面相关代码都要删掉，不知道会不会影响程序正常逻辑，还是换个编译环境算了。

**Comment by Richard-Cao** [comment]
@Jeffreyli1983 不会影响正常逻辑，只有feedback不能用了而已
