### ISSUE TITLE
装好后一直停留在启动页

### ISSUE THREAD

**Issue by Paidaxi** [attentiveness/reading#80]

**Comment by Richard-Cao** [comment]
本地run的？

**Comment by Paidaxi** [comment]
对 debug到真机上 wiff也连了 就卡在启动页，我自己init项目自己跑，是没问题的

**Comment by Richard-Cao** [comment]
server起了没，有什么报错信息么

**Comment by Paidaxi** [comment]
ERROR  EPERM: operation not permitted, lstat 'c:\reading-master\android\app\bui
ld\intermediates\res\merged\debug\anim'
{"errno":-4048,"code":"EPERM","syscall":"lstat","path":"c:\\reading-master\\andr
oid\\app\\build\\intermediates\\res\\merged\\debug\\anim"}
Error: EPERM: operation not permitted, lstat 'c:\reading-master\android\app\buil
d\intermediates\res\merged\debug\anim'
在run-android后，server报的错，但是apk安装成功了且一直停留在启动页

**Comment by Richard-Cao** [comment]
那肯定……server都报错了呀，查下server报错信息

**Comment by Richard-Cao** [comment]
请使用react-native start的方式起server。在项目根目录下。
