### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by guai-ak** [attentiveness/reading#81]
![simulator screen shot 2017 7 6 7 49 42](https://user-images.githubusercontent.com/13192063/27909648-44748b3c-6284-11e7-96de-83c31bce09ef.png)

**Comment by Richard-Cao** [comment]
Android还是iOS？

**Comment by Richard-Cao** [comment]
你的react-native版本是？

**Comment by Jiangjinjin1** [comment]
"react-native": "0.28.0",

**Comment by Richard-Cao** [comment]
0.28？ @Jiangjinjin1 这个版本太低了

**Comment by guai-ak** [comment]
0.44.0

**Comment by Jiangjinjin1** [comment]
npm run test 的结果，react-native的版本是0.44.3的

**Comment by Richard-Cao** [comment]
请在项目根目录下使用react-native start方式起server，就不会有这个问题。目前官方的起server方式有点小问题。

**Comment by Richard-Cao** [comment]
现在最新的master代码已经修复 Xcode起的server也没问题
