### ISSUE TITLE
   TypeError: Cannot read property 'mark' of undefined

### ISSUE THREAD

**Issue by nullllun** [attentiveness/reading#82]
npm test的时候，出现该问题：
FAIL  app\sagas\_spec_\read.spec.js
  ● Test suite failed to run

    TypeError: Cannot read property 'mark' of undefined

      at Object.<anonymous> (app/sagas/read.js:57:810)
      at Object.<anonymous> (app/sagas/_spec_/read.spec.js:20:11)

如果是用react-native run-android，出现一样的问题：
undefined is not an object (evaluating 'regeneratorRuntime.mark')
<unknown>

网络上找了一些资料，未能解决：
https://github.com/facebook/react-native/issues/14838

求解答，谢谢

**Comment by Richard-Cao** [comment]
你的node版本是多少？

如果是run起来出现undefined is not an object (evaluating 'regeneratorRuntime.mark')错误的话，请使用`react-native start`命令起server，然后再run

**Comment by nullllun** [comment]
@Richard-Cao  node 版本为6.9.1 ，模拟器用的是夜神模拟器，开发工具 idea 2017.02
react-native start运行完后运行react-native start。 dev setting也改自己ip和端口了。
除了上面的错误外，还出现了新的错误：
console.error: "
[redux-logger v3] BREAKING CHANGE
[redux-logger v3] Since 3.0.0 redux-logger exports by default logger with default settings.
[redux-logger v3] Change
[redux-logger v3] import createLogger from 'redux-logger'
[redux-logger v3] to
[redux-logger v3] import { createLogger } from 'redux-logger'
"
T

**Comment by Richard-Cao** [comment]
你删了node_modules然后拉最新的代码，重新npm install试试~

**Comment by nullllun** [comment]
可以了，是环境问题
