### ISSUE TITLE
更换react@16.0.0-alpha.12和react-native@0.45.1，ios模拟报错

### ISSUE THREAD

**Issue by yusemo** [attentiveness/reading#83]
![image](https://user-images.githubusercontent.com/3362228/28159628-273a68fe-67f0-11e7-8548-982e47722aa7.png)

之后整个项目删除，回滚be30fac93a0c55cbb03611e813e07415a50d52b7  （2017-07-04 16:17）版本 从新执行就可行

测试环境：
xcode：8.3.3
node：8.1.2
react-native-cli: 2.0.1
react-native: 0.44.3

**Comment by Richard-Cao** [comment]
你这个是网的问题，glog是个第三方模块，你没下载下来……

**Comment by yusemo** [comment]
@Richard-Cao 我利用网上的方法下载了别人的.rncache 里面的内容按照这里的做法http://vanessa.b3log.org/articles/2017/06/12/1497235254333.html 
之后报错
![image](https://user-images.githubusercontent.com/3362228/28197424-67941adc-6889-11e7-8952-a96681a4f968.png)
请问你有安装的包么？或者告诉下我怎么找到这个glog0.3.4.tar.gz 的安装包呢？网上都是0.3.3版本。谢谢

**Comment by Richard-Cao** [comment]
@yusemo 这个只要你的网是正常翻墙的，都可以下载下来……我是自动下载好的，没这个包……

**Comment by YuZhongMa** [comment]
1.rm -rf node_moudles
2.把react-native 切换到0.44.0，然后npm（解决版本太高文件下载不了问题）
3.然后xcode里  Target->build phases->run script only when install勾选（未安装不必要sh可以不运行）
目前可稳定运行，亲测

**Comment by sunfuhao** [comment]
loushang shi sb

**Comment by yusemo** [comment]
@Richard-Cao 最后https://codeload.github.com/google/glog/tar.gz/v0.3.4  
下载完毕后 放入/Users/YOUCOUNT/.rncache 
开启了全局模式的墙，delete node_modules再从新执行一边安装
building前再切换墙自动代理模式（不然会有坑，比如make sure you’re running a packager server or have included a .jsbundle file in your application bundle的错误）
解决了我一直新版本的问题。感激作者还继续维护！
如果可以可否加qq交流，有些源码想请教下。谢谢

**Comment by Richard-Cao** [comment]
@yusemo 可以。403164405
