### ISSUE TITLE
安卓运行报错，错误代码如下（运行我自己的项目没有这种问题）

### ISSUE THREAD

**Issue by Wen-Ge** [attentiveness/reading#84]
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by Richard-Cao** [comment]
执行`adb devices`看看，报错信息是没连上设备

**Comment by Wen-Ge** [comment]
我用的是Android studio的模拟器，回家我用真机试一下

**Comment by Richard-Cao** [comment]
@Wen-Ge 怎么样了

**Comment by Wen-Ge** [comment]
没问题了，应该是项目来回切换，serve没有成功启动
