### ISSUE TITLE
Excuse me, what is wrong with the below issue. how to solve it?

### ISSUE THREAD

**Issue by yingjinWong** [attentiveness/reading#88]
undefined is not a function (evaluating 'Object.getOwnPropertyNames(t)[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')
y
    E:\ReactNative\reading-master\node_modules\leancloud-storage\dist\av-rn-min.js:1:21217
_extend
    E:\ReactNative\reading-master\node_modules\leancloud-storage\dist\av-rn-min.js:1:24496
exports
    E:\ReactNative\reading-master\node_modules\leancloud-storage\dist\av-rn-min.js:1:75206
<unknown>
    E:\ReactNative\reading-master\node_modules\leancloud-storage\dist\av-rn-min.js:8:143
e
    E:\ReactNative\reading-master\node_modules\leancloud-storage\dist\av-rn-min.js:1:390
<unknown>
    E:\ReactNative\reading-master\node_modules\leancloud-storage\dist\av-rn-min.js:1:770
<unknown>
    E:\ReactNative\reading-master\node_modules\leancloud-storage\dist\av-rn-min.js:1:779
<unknown>
    E:\ReactNative\reading-master\node_modules\leancloud-storage\dist\av-rn-min.js:1:82
<unknown>
    E:\ReactNative\reading-master\node_modules\leancloud-storage\dist\av-rn-min.js:1:262
loadModuleImplementation
    E:\ReactNative\reading-master\node_modules\metro-bundler\src\Resolver\polyfills\require.js:174:12
guardedLoadModule
    E:\ReactNative\reading-master\node_modules\metro-bundler\src\Resolver\polyfills\require.js:126:36
_require
    E:\ReactNative\reading-master\node_modules\metro-bundler\src\Resolver\polyfills\require.js:110:20
<unknown>
    E:\ReactNative\reading-master\app\pages\Splash.js:22
loadModuleImplementation
    E:\ReactNative\reading-master\node_modules\metro-bundler\src\Resolver\polyfills\require.js:174:12
guardedLoadModule
    E:\ReactNative\reading-master\node_modules\metro-bundler\src\Resolver\polyfills\require.js:126:36
_require
    E:\ReactNative\reading-master\node_modules\metro-bundler\src\Resolver\polyfills\require.js:110:20
<unknown>
    E:\ReactNative\reading-master\app\containers\app.js:19
loadModuleImplementation
    E:\ReactNative\reading-master\node_modules\metro-bundler\src\Resolver\polyfills\require.js:174:12
guardedLoadModule
    E:\ReactNative\reading-master\node_modules\metro-bundler\src\Resolver\polyfills\require.js:126:36
_require
    E:\ReactNative\reading-master\node_modules\metro-bundler\src\Resolver\polyfills\require.js:110:20
<unknown>
    E:\ReactNative\reading-master\app\root.js:22
loadModuleImplementation
    E:\ReactNative\reading-master\node_modules\metro-bundler\src\Resolver\polyfills\require.js:174:12
guardedLoadModule
    E:\ReactNative\reading-master\node_modules\metro-bundler\src\Resolver\polyfills\require.js:126:36
_require
    E:\ReactNative\reading-master\node_modules\metro-bundler\src\Resolver\polyfills\require.js:110:20
<unknown>
    E:\ReactNative\reading-master\index.android.js:19
loadModuleImplementation
    E:\ReactNative\reading-master\node_modules\metro-bundler\src\Resolver\polyfills\require.js:174:12
guardedLoadModule
    E:\ReactNative\reading-master\node_modules\metro-bundler\src\Resolver\polyfills\require.js:119:45
_require
    E:\ReactNative\reading-master\node_modules\metro-bundler\src\Resolver\polyfills\require.js:110:20
global code

**Comment by Richard-Cao** [comment]
What's your node version?

**Comment by dytiz** [comment]
你好，我也遇到同样的问题,  
node:v7.0.0 
"react": "16.0.0-alpha.12",
"react-native": "0.47.1",

**Comment by dytiz** [comment]
根据报错信息找到了Splash.js的22行，发现是leancloud-storage这个出现的问题。
查看package.json该版本是3.1.0 ，然后将其写在换成了3.0.4,就可以跑起来了。
npm   info  leancloud-storage    //查看版本信息
npm uninstall --save leancloud-storage   //卸载3.1.0
npm install --save leancloud-storage@3.0.4

**Comment by Richard-Cao** [comment]
@dytiz Thx! I will update `package.json`

**Comment by Richard-Cao** [comment]
Please `git pull` master branch.
