### ISSUE TITLE
ListView组件已过期？

### ISSUE THREAD

**Issue by dongjunwu** [attentiveness/reading#90]
在react native中文网查看ListView组件，上面写道“此组件已过期 - 请使用FlatList或SectionList代替。”

**Comment by Richard-Cao** [comment]
不建议看中文网，直接看官网就可以。不同的控件使用场景不同

**Comment by dongjunwu** [comment]
谢谢您的回复。我是一个初学者，最近看了一些教材，然后一边尝试学习您这个项目的代码。有一个地方我一直没弄明白，就是导航NavigationUtil.reset(this.props.navigation, 'Home')进入MainContainer.js的时候，store里就有了read对象，它是如何获得的？希望您能望指教一下，谢谢。

**Comment by Richard-Cao** [comment]
你可以看下https://github.com/attentiveness/reading/blob/master/app/root.js和https://github.com/attentiveness/reading/blob/master/app/store/configure-store.js

**Comment by dongjunwu** [comment]
嗯，这两个文件好象没有获取read对象的操作？我看了好象是在进入MainContainer.js之前store里都没有这个read，进入MainContainer.js之后就有了，但MainContainer.js里又没有找到相关的代码，我知道这是因为我还没看懂，只是不知道是在哪里，所以比较困惑，还望再指教一下，非常非常感谢。
