### ISSUE TITLE
按照reading项目 在自己项目中使用redux-saga  报regeneratorRuntime.mark错误

### ISSUE THREAD

**Issue by wangliguang** [attentiveness/reading#91]
您好，我按照您的方式在项目中使用react-saga，出现如下错误，

**undefined is not an object (evaluating regeneratorRuntime.mark) 。**

我在网上查找资料说是因为babel无法转换ES6的函数生成器，我试了好几个网上的教程都不管用，但我运行你的项目就能正常运行起来。甚至我将你的package.json里面的内容复制过来重新npm install还是不行。
 
谢谢您的浏览，希望能得到您的指点。

**Comment by Richard-Cao** [comment]
把reading的代码拉到最新 重新npm install就可以，现在的reading是没有这个问题的

**Comment by Richard-Cao** [comment]
和babel有关，babel-preset-react-native，还有对应的react版本，你可以看下

**Comment by wangliguang** [comment]
`"dependencies": {
		"react": "16.0.0-alpha.12",
		"react-native": "0.47.1",
		"react-redux": "^5.0.6",
		"redux": "^3.7.2",
		"redux-logger": "^3.0.6",
		"redux-saga": "^0.15.6"
	},
	"devDependencies": {
		"babel-jest": "20.0.3",
		"babel-preset-react-native": "3.0.0",
		"jest": "20.0.4",
		"react-test-renderer": "16.0.0-alpha.12"

	},`

上面是我package上的内容，我重新删过缓存也删除过node包重装，但都没用，您在使用saga出现过这个错误么，还是说您装过saga以后可以直接使用。

**Comment by Richard-Cao** [comment]
当然可以，reading里现在就有saga 你的`babel-preset-react-native`版本太新了，回退到reading使用的版本就可以了

**Comment by wangliguang** [comment]
我把babel-preset-react-native 恢复到2.0.0，然后将node包删除，重新npm install，还是报上面说的错误

**Comment by Richard-Cao** [comment]
清下npm缓存。reading这么配置之后就没问题了。主要就是几个语法糖的不兼容

**Comment by wangliguang** [comment]
谢谢您的引导，通过下面几步我解决了问题

1. npm i babel-preset-react-native@2.0.0 -D -S  （**千万不能直接在package.json里面将3.0.0改为2.0.0**）

2. npm start -- --reset-cache

**Comment by Richard-Cao** [comment]
其实直接改也可以，不过你问题解决了就行，哈哈
