### ISSUE TITLE
react-native start运行一直停留在Loading dependency graph, done.

### ISSUE THREAD

**Issue by xiaoyupao** [attentiveness/reading#96]
大神，我执行  $ react-native start 命令，一直停留在这里，是什么原因呢？
求解决跑起项目，谢谢

MacBook-Pro:reading $ react-native start
Scanning 742 folders for symlinks in /Users/www/mycode/reading/node_modules (5ms)
 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.    │
 │    │
 │  Keep this packager running while developing on any JS projects. Feel    │
 │  free to close this tab and run your own packager instance if you    │
 │  prefer.    │
 │    │
 │  https://github.com/facebook/react-native    │
 │    │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   /Users/www/mycode/reading

React packager ready.

Loading dependency graph, done.

**Comment by Richard-Cao** [comment]
这是正常的呀，起了server然后你build项目就可以了。。。

**Comment by caiya** [comment]
@Richard-Cao build项目是啥意思呢，第一天接触rn

**Comment by Richard-Cao** [comment]
@caiya 就是react-native run-xxx，或者你用XCode/Android Studio直接Run项目也可以。

**Comment by caiya** [comment]
@Richard-Cao 多谢楼主
