### ISSUE TITLE
项目爆出了65536的问题

### ISSUE THREAD

**Issue by JeeseC** [attentiveness/reading#97]
* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.pro
cess.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.
DexIndexOverflowException: method ID not in [0, 0xffff]: 65536

React-Native一个个更新，更新完了之后，好不容易不出问题了，却出现了这个安卓的经典问题。
请问大神需要怎么调试才能运行起来

**Comment by Richard-Cao** [comment]
clean了之后重新build吧。我总共也就一万多个方法。。。这是因为你编译过程出了什么问题吧

**Comment by JeeseC** [comment]
@Richard-Cao  在命令行中执行了以下命令
`cd android 
gradlew clean 
cd ..
react-native run-android’

清理之后也是没办法运行起来，我在编译的过程中也没有出现问题，一切都是正常执行

**Comment by Richard-Cao** [comment]
今晚回家我看看这个问题。

**Comment by JeeseC** [comment]
@Richard-Cao 非常感谢

**Comment by AKMaS** [comment]
https://stackoverflow.com/questions/32836059/unexpected-top-level-exception-com-android-dex-dexindexoverflowexception-metho


参考这个

然而运行成功后一直卡在启动页

**Comment by Richard-Cao** [comment]
我刚用最新的代码编译android，一切正常，并没有遇到你们说的65535问题。我这个APP很小，总共也就一万多个方法，你们的gradle版本是多少？

**Comment by Richard-Cao** [comment]
没啥问题我就先关掉这个issue了哦，如果有什么问题可以继续追加
