### ISSUE TITLE
求解项目在安卓上跑不起来

### ISSUE THREAD

**Issue by meyer-net** [attentiveness/reading#98]
$ react-native run-android
Scanning 723 folders for symlinks in E:\Sync\react-project\dva\reading\node_modules (56ms)
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat installDebug)...
Download https://jcenter.bintray.com/org/codehaus/plexus/plexus-utils/3.0.17/plexus-utils-3.0.17.jar

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'reading'.
> Could not resolve all files for configuration ':classpath'.
   > Could not download sisu-guice-no_aop.jar (org.sonatype.sisu:sisu-guice:3.1.0)
      > Could not get resource 'https://jcenter.bintray.com/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar'.
         > Could not GET 'https://jcenter.bintray.com/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar'.
            > Received fatal alert: bad_record_mac

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 46.55 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

-----------------------------
求大神解救。
react-native start 只是启动了。

![image](https://user-images.githubusercontent.com/16422453/30906820-8caf0cc0-a3ab-11e7-9fd3-0ff1f30854e2.png)

**Comment by Richard-Cao** [comment]
你这是某个包没下下来吧？目测网络问题……

**Comment by meyer-net** [comment]
诶，react-native run-android 始终还是没能跑起来。现在又报错

**Comment by meyer-net** [comment]
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by Richard-Cao** [comment]
有没有更具体一些的报错信息？因为我本地一直没问题……CI上也没问题

**Comment by meyer-net** [comment]
重新git clone，然后npm i，运行react-native run-android。总是跑不起来。有时候停留在下载页面。

**Comment by Richard-Cao** [comment]
这是你本地网络的问题……基本上都是在下载东西

**Comment by meyer-net** [comment]
![image](https://user-images.githubusercontent.com/16422453/30999187-2b4529e0-a506-11e7-98dd-5cd7b11fccd0.png)
可算缴尽脑汁找到可用的VPN给弄完了.但是出现红屏错误.

**Comment by meyer-net** [comment]
应该是我同时跑了 别的APP的原因.我关掉看看.

**Comment by meyer-net** [comment]
成功运行,感谢.都是网络的问题.

**Comment by Richard-Cao** [comment]
那没啥问题我就关掉这个issue啦
