### ISSUE TITLE
org.gradle.jvmargs 配置

### ISSUE THREAD

**Issue by hsay** [attentiveness/reading#99]
![default](https://user-images.githubusercontent.com/18224948/31007019-a1eacf34-a531-11e7-9faa-12bfd3ea1cd2.png)
看你的配置文件设置为org.gradle.jvmargs=-Xmx1536m(文件：gradle.properties)，这里为什么要设置这么大呢？

**Comment by Richard-Cao** [comment]
其实你设置小点也行……我设置大点主要是为了优化编译速度

**Comment by hsay** [comment]
@Richard-Cao 谢谢回复。我是32位机，这个设置太大了，没法正常编译。
另外：启动白屏问题，就是在App启动图与加载的第一个展示组件Splash之间存在白屏现象，可以使用react-native-splash-screen来处理？
另外：调试模式下，进入App然后退出再次进入会报错“SDK is already initialized”，需要重新reload才可以。

**Comment by Richard-Cao** [comment]
设置太大了你可以改小点~
react-native-splash-screen是可以的
你说的“SDK is already initialized”是哪个SDK？

**Comment by hsay** [comment]
![_20170929173802](https://user-images.githubusercontent.com/18224948/31010308-fdb0b4ae-a53c-11e7-8902-b4a5ff98275a.jpg)
小米4手机，必现。

**Comment by Richard-Cao** [comment]
明白了。我回头看下这个问题，应该是leancloud-storage依赖库的问题

**Comment by Richard-Cao** [comment]
这个问题已经修复。请更新代码到最新的master分支就可以。
